// English version of the sprint plan data (portal/plan/data.js). Keep the structure identical to the Chinese file:
// the checklists are stored by index, so both languages share the same progress. tools/i18n.py check compares the two.
window.AIG_PLAN = (function () {
  "use strict";

  var BOOK = { python: "Python", cpp: "C++", cs: "CS", math: "Math", llm: "LLM", torch: "PyTorch", scratch: "From scratch", cuda: "CUDA", train: "Training", serving: "Inference", minisgl: "mini-sglang", media: "Image & Video", sglang: "SGLang History", omni: "SGLang-Omni" };
  function L(book, path, title) { return [book, path, title]; }
  function E(url, title) { return ["ext", url, title]; }
  var U = {
    cs336: "https://stanford-cs336.github.io/spring2025/", dlsys: "https://dlsyscourse.org/", mlsys: "https://mlsyscourse.org/",
    efficientml: "https://hanlab.mit.edu/courses/2024-fall-65940", scaling: "https://jax-ml.github.io/scaling-book/",
    playbook: "https://huggingface.co/spaces/nanotron/ultrascale-playbook", mleng: "https://github.com/stas00/ml-engineering",
    mamf: "https://github.com/stas00/ml-engineering/tree/master/compute/accelerator/benchmarks",
    allreduce: "https://github.com/stas00/ml-engineering/tree/master/network/benchmarks",
    gpumode: "https://github.com/gpu-mode/lectures", kernelbot: "https://github.com/gpu-mode/reference-kernels",
    leetcuda: "https://github.com/xlite-dev/LeetCUDA", gpuPuzzles: "https://github.com/srush/GPU-Puzzles",
    tritonPuzzles: "https://github.com/srush/Triton-Puzzles", tensorPuzzles: "https://github.com/srush/Tensor-Puzzles",
    trainPuzzles: "https://github.com/srush/LLM-Training-Puzzles", nanovllm: "https://github.com/GeeeekExplorer/nano-vllm",
    bentoml: "https://bentoml.com/llm/", zomi: "https://github.com/Infrasys-AI/AIInfra", aig: "https://caomaolufei.github.io/AIInfraGuide/interview/",
  };

  // ---------------------------------------------------------------- Target abilities
  var ABILITIES = [
    { c: "c-blue", t: "Coding and algorithms", why: "The first gate in every interview, and the most underestimated one.", pass: [
      "Solve a LeetCode medium correctly in one go within 25 minutes; for a hard one, give a workable idea and its complexity",
      "All of Hot 100 plus about 100 topic problems; redo every problem you got wrong",
      "Hand-write 20 common inference-system components on the spot (attention, sampling, Radix Cache, thread pool...)",
      "Write both Python and C++: inference systems are split about half and half between them"],
      verify: "Weekly timed mocks: medium problems solved in one go within 25 minutes at least 70% of the time; hand-written components pass the exercise judge within the time limit",
      links: [L("serving", "career/coding", "Coding questions"), ["practice", "", "Exercise bank"]] },
    { c: "c-indigo", t: "C++ and systems programming", why: "Open-source inference libraries (communication, kernels, storage) are largely C++; without reading it you cannot discuss the details.", pass: [
      "Idiomatic modern C++: RAII, move semantics, smart pointers, templates and constexpr",
      "Concurrency: threads, atomics, memory order, lock-free queues, thread pools",
      "Read and modify C++ / CUDA engineering code at the level of DeepEP, FlashInfer and Mooncake",
      "Expose implementations to Python with pybind11 / PyTorch C++ extensions, and track down problems with sanitizers and perf"],
      verify: "C++ exercises pass the judge with no ASan / TSan / UBSan reports; find and fix a small issue in an open-source C++ project",
      links: [L("cpp", "basics/value-raii", "Value semantics and RAII"), L("cpp", "concurrency/atomics", "Memory order"), L("cpp", "engineering/reading-code", "Reading inference libraries")] },
    { c: "c-orange", t: "GPUs and CUDA", why: "Inference optimization ends up in kernels and bandwidth, and interviews drill down to hardware numbers.", pass: [
      "Explain SMs, warps, the memory hierarchy and Tensor Cores, and remember the key numbers of the H100 / H800",
      "Hand-write a reduction, a transpose, a tiled GEMM, online softmax and the FlashAttention forward pass",
      "Find the bottleneck with Nsight Compute and say in numbers how far you are from the roofline",
      "Write fused kernels in Triton; understand what Hopper's TMA, WGMMA and FP8 do"],
      verify: "The exercises' GPU emulator checks memory access and races; real-GPU performance bar: reduction ≥ 80% of measured bandwidth, SGEMM ≥ 70% of cuBLAS, Tensor Core HGEMM ≥ 60% of cuBLAS, Triton FlashAttention forward ≥ 60% of FA2",
      links: [L("cuda", "kernels/gemm", "The road to a fast GEMM"), L("cuda", "advanced/attention", "FlashAttention"), L("cuda", "tools/profiling", "Nsight")] },
    { c: "c-purple", t: "How LLMs work, and numerics", why: "Every optimization in an inference system comes back to the model's structure and numerical precision.", pass: [
      "Derive the forward and backward passes of attention, the FFN, RoPE and RMSNorm by hand",
      "MLA's low-rank compression and matrix absorption, MoE routing and load balancing, how MTP works",
      "Where FP8 / INT4 quantization error comes from, and scaling granularity",
      "For any model, estimate the parameter count, FLOPs, KV cache size and the bandwidth bound of decode"],
      verify: "Self-tests ≥ 85%; estimation questions within 10% of a model or a measurement; derivations written within the time limit",
      links: [L("llm", "transformer/attention-variants", "MQA / GQA / MLA"), L("llm", "transformer/moe", "MoE"), L("llm", "inference/estimation", "Estimation"), ["practice", "?q=估算", "Estimation questions"]] },
    { c: "c-green", t: "Inference engines", why: "The heart of the job: explain every step from request to token, and every trade-off along the way.", pass: [
      "Draw SGLang / vLLM's whole flow from request to returned token, and explain each design trade-off",
      "Hand-write a paged KV cache, continuous batching, prefix caching, chunked prefill, overlap scheduling and CUDA Graph",
      "Get your own engine running on a GPU, and benchmark and ablate it against SGLang",
      "Have at least one PR merged into a mainstream inference framework"],
      verify: "Your implementation's greedy output matches Hugging Face token for token; throughput ≥ 60% of SGLang on the same GPU and load; an ablation report; a merged PR",
      links: [L("serving", "engine/overview", "Building an inference engine from scratch"), L("minisgl", "overview/architecture", "mini-sglang from scratch"), L("serving", "source/sglang", "SGLang source")] },
    { c: "c-teal", t: "Distributed inference and large-scale deployment", why: "LLM inference is a large multi-node, multi-GPU system; system design questions almost always land here, and training-side parallelism comes up too.", pass: [
      "The communication pattern and volume of TP / EP / PP / CP",
      "DeepEP's high-throughput and low-latency modes; the roles of RDMA, NVLink and NVSHMEM",
      "PD disaggregation and KV transfer; multi-tier cache architectures centered on the KV cache",
      "Training side: DP / ZeRO / FSDP, Megatron TP + SP, PP schedules; work out the memory budget and communication volume",
      "Design an online service for a MoE model with hundreds of billions of parameters, with estimates for machines, throughput and latency"],
      verify: "Multi-process TP / EP / PP / DDP (gloo on CPU is fine) matches a single process numerically; measure all-reduce bus bandwidth and explain the gap to theory; memory budget within 15% of measurement",
      links: [L("serving", "distributed/expert-parallel", "Expert parallelism"), L("serving", "distributed/pd-disagg", "PD disaggregation"), L("train", "data/zero-fsdp", "ZeRO and FSDP"), L("train", "practice/strategy", "Combining and choosing parallelism"), L("serving", "comm/nvshmem-deepep", "NVSHMEM and DeepEP"), L("serving", "comm/kv-storage", "KV transfer and storage")] },
  ];

  // ---------------------------------------------------------------- Three kinds of roles
  var DIRS = [
    ["Day to day",
      "Scheduling, KV management, parallelism; supporting new models and building features",
      "Attention, GEMM, MoE and quantization kernels and communication operators; profiling and end-to-end tuning",
      "Large-scale deployment, PD disaggregation, KV cache pools, routing and autoscaling; stability and cost"],
    ["What interviews test",
      "The engine's whole flow and each design trade-off; source details; hand-writing schedulers and caches",
      "Writing CUDA / Triton on the spot; key hardware numbers; roofline analysis and numerical precision",
      "System design and capacity estimation; communication and storage; failure handling and scaling"],
    ["Code to read",
      "SGLang, vLLM, mini-sglang, and the calling side of FlashInfer",
      "FlashAttention, FlashMLA, DeepGEMM, CUTLASS / CuTe, the Triton tutorials",
      "Mooncake, NVIDIA Dynamo, LMCache, llm-d, SGLang Model Gateway"],
    ["Where it is in the plan", "Weeks 5–8 + project A", "Weeks 2–3, 10, 13 + project C", "Weeks 9, 11–12, 14 + project B"],
  ];

  // ---------------------------------------------------------------- Levels and how to verify them
  var LEVELS = [
    { c: "c-blue", k: "L1", t: "Explain", d: "Say what it is and why in one sentence and one key number, and handle one follow-up question.",
      how: ["Chapter self-tests and self-test banks ≥ 85% correct", "Talk to a blank page for 3 minutes, record it and listen for gaps", "Turn it into interview flashcards"] },
    { c: "c-green", k: "L2", t: "Write it right", d: "Write an implementation that passes the tests without looking anything up, with the edge cases right.",
      how: ["Exercise judge: browser, local, GPU", "GPU emulator: out-of-bounds, races, coalescing, bank conflicts", "Match a reference implementation token by token / element by element"] },
    { c: "c-orange", k: "L3", t: "Make it fast", d: "Write it within a time limit; reach the performance bar on a real GPU; estimates within range of measurements.",
      how: ["Timed hand-writing: 20–45 minutes", "Real-GPU performance bar: a ratio against cuBLAS, FA2, SGLang", "Estimation questions: within 10% of a model or a measurement"] },
    { c: "c-purple", k: "L4", t: "Deliver", d: "Turn it into something others can reproduce and evaluate, and that holds up under questions.",
      how: ["Projects: baseline comparison, ablations, reproducible in 10 minutes", "Merged PRs, blog posts, leaderboard ranks", "Mock interview rubric"] },
  ];
  var TOOLBOX = [
    ["Chapter self-tests and self-test banks", "Are the concepts clear", "Self-tests at the top of every chapter, the LLM book's self-test bank, the CUDA and inference interview question banks", "Every chapter / week"],
    ["Exercise judge", "Is the implementation correct", "Exercises: one-click judging in the browser; local judge.py (macOS / WSL2 + GPU)", "Every week"],
    ["GPU emulator", "Are memory access patterns and concurrency correct", "The GPU emulator in the exercises: coalescing, bank conflicts, race detection, barrier divergence", "Weeks 2–3"],
    ["Real-GPU performance bar", "Is it fast enough", "judge.py bench measures this machine's bandwidth and compute as the denominator; bronze / silver / gold tiers for CUDA C++ exercises; Nsight Compute; the GPU MODE leaderboard", "Weeks 2, 3, 7, 10, 13"],
    ["Estimation questions", "Quantitative reasoning", "The estimation questions in the exercises (20 of them, search for “估算”), the Scaling Book's exercises; compare estimates with measurements", "Weeks 4, 9, 14"],
    ["Timed hand-writing", "Speed under interview conditions", "A timer plus the list of hand-written components (most have matching exercises)", "Every week"],
    ["Project acceptance", "End-to-end delivery", "Baseline comparison, ablations, reproduction notes, load-test report", "Weeks 7, 12, 13"],
    ["Mock interviews", "Presentation and follow-ups", "The \"Mock interviews\" chapter of the inference systems book: 60 minutes in four parts, scored on correctness, depth, numbers and communication, with a review template", "Weekly from week 9"],
    ["External signals", "Are you recognized", "Merged PRs, blog readership and feedback, leaderboard ranks", "From week 8"],
  ];

  // ---------------------------------------------------------------- Courses and tutorials used
  var REFS = [
    ["Stanford CS336: Language Modeling from Scratch", U.cs336, "Weeks 1, 3, 9",
      "Assignment 1 (tokenizer, model, optimizer, training a small model from scratch) as an optional assignment; assignment 2 (profiling, FlashAttention2 in Triton, DDP and sharded optimizers) split across weeks 3 and 9", "Assignments come with tests and leaderboards"],
    ["CMU 10-414 Deep Learning Systems", U.dlsys, "Week 3 (optional)", "The needle assignments: write automatic differentiation and a strided NDArray with CPU / GPU backends from scratch, to fill in PyTorch internals", "Autograded"],
    ["CMU 15-442 Machine Learning Systems", U.mlsys, "Week 1", "Read through the syllabus to find gaps: frameworks, compilation, parallelism and serving at a glance", ""],
    ["MIT 6.5940 EfficientML", U.efficientml, "Weeks 4, 10", "Lectures on quantization, pruning and sparsity, distillation and LLM deployment; the AWQ and 2:4 sparsity labs", "Labs have accuracy bars"],
    ["How to Scale Your Model (the JAX Scaling Book)", U.scaling, "Weeks 4, 9", "Rooflines, Transformer math, parallelism for training and inference, the GPU chapter; use each chapter's exercises as estimation practice", "Exercises with answers"],
    ["Hugging Face Ultra-Scale Playbook", U.playbook, "Week 9", "The main text on distributed training: DP → ZeRO → TP / SP → CP → PP → EP; read it alongside this site's distributed training book, it has more measurements", "Memory budgets against measurements"],
    ["ML Engineering (Stas Bekman)", U.mleng, "Weeks 2, 9, 14", "Hardware, networking, storage, debugging; measure your own machines with mamf-finder and all_reduce_bench", "Measured numbers"],
    ["GPU MODE lectures + PMPP 4th edition", U.gpumode, "Weeks 2–3, 6, 10", "Lectures on performance checklists, reduction, Tensor Cores, CUTLASS / CuTe, FlashInfer, SGLang performance and more, with the PMPP textbook", ""],
    ["The GPU MODE leaderboard (KernelBot)", U.kernelbot, "Week 13", "PMPP exercises and kernel competition problems, judged on real GPUs", "Real-GPU leaderboard"],
    ["LeetCUDA", U.leetcuda, "Weeks 3, 10, 13", "More than 200 CUDA / Triton / CuTe kernels; pick 20–30 by difficulty, with a focus on HGEMM and FA2-MMA", "Performance against cuBLAS and FA2"],
    ["The Puzzles series (Sasha Rush)", U.gpuPuzzles, "Weeks 1–3, 9", "Four sets of puzzles (Tensor, GPU, Triton, LLM Training) as a warm-up for each phase", "Built-in tests"],
    ["nano-vllm", U.nanovllm, "Weeks 5–7", "A vLLM rewrite in about 1,200 lines, to read alongside mini-sglang", ""],
    ["LLM Inference Handbook (BentoML)", U.bentoml, "Weeks 11, 14", "An overview of inference metrics, optimizations, deployment and operations", ""],
    ["AIInfra (ZOMI)", U.zomi, "Weeks 9, 14", "A Chinese course: AI clusters, communication and storage, containers and cloud native, distributed training and inference, with MFU modeling code", ""],
    ["AIInfraGuide interview guide", U.aig, "Weeks 14–16", "About 200 real interview reports, grouped by topic into mock questions", "Mock interviews"],
  ];

  // ---------------------------------------------------------------- Standing out
  var EDGE = [
    { c: "c-blue", t: "Main line: the inference systems basics", why: "Every candidate has to clear this; below this line, nothing else can amplify you.", pass: [
      "Explain and write the four essentials: scheduling, KV management, distribution and performance analysis",
      "C++ / CUDA good enough to read and modify open-source infrastructure libraries",
      "A full mini-sglang rebuild plus a performance report, as the most basic project"] },
    { c: "c-orange", t: "Amplifier 1: Rust and systems engineering", why: "Inference platforms increasingly use Rust for the data plane: SGLang's Router / Model Gateway and Hugging Face tokenizers are written in Rust.", pass: [
      "Project B: a PD-aware, cache-aware inference gateway in Rust",
      "Turn what you learn from the gateway into PRs to SGLang's Rust gateway",
      "Argue with numbers: tail latency, throughput and cache hit rate against a baseline"] },
    { c: "c-purple", t: "Amplifier 2: large-system architecture", why: "System design interviews separate candidates the most: PD disaggregation, KV cache pools, multi-tenancy and global scheduling are all distributed systems problems at heart.", pass: [
      "10 inference system design questions, each with capacity estimates, failure domains and a scaling plan",
      "Talk about inference systems in the general language of distributed systems: scheduling, caching, transfer, isolation, observability",
      "Compare two large-scale inference architectures as interview material: a disaggregated architecture centered on the KV cache, and large-scale expert parallelism with PD disaggregation"] },
    { c: "c-teal", t: "Amplifier 3: runtimes and tooling", why: "An inference engine is itself a runtime: event loops, task scheduling, memory pools, asynchronous execution (CUDA streams / graphs), zero copy.", pass: [
      "Explain overlap scheduling, CUDA Graph and KV memory management from a runtime perspective, in your own terms",
      "Project D (optional): an inference performance visualization / scheduling replay tool that turns profiler output and engine logs into an interactive timeline",
      "Demonstrating the tool on a real performance problem in an interview is very memorable"] },
  ];

  // ---------------------------------------------------------------- Phases and weeks
  var PHASES = [
    { c: "c-blue", name: "Phase 1 · Foundations", weeks: [1, 5] },
    { c: "c-green", name: "Phase 2 · Into the frameworks", weeks: [6, 9] },
    { c: "c-orange", name: "Phase 3 · Frontier topics and portfolio", weeks: [10, 13] },
    { c: "c-pink", name: "Phase 4 · Interview sprint", weeks: [14, 17] },
  ];

  var WEEKS = [
    { t: "Diagnosis + Transformer review + starting C++", g: "Find out where you stand; review the Transformer forward pass until you can write it by hand. Math is a book of its own; look it up when you need it.",
      learn: [L("setup", "", "Setup: one-click environment (works on a Mac)"), L("llm", "synthesis/quiz", "Self-test questions (diagnose first)"), L("math", "", "Math Fundamentals: look it up when needed (take its self-test to see where you stand)"),
        L("llm", "transformer/attention", "Attention"), L("llm", "transformer/position", "RoPE"), L("llm", "transformer/norm-residual", "Normalization and residuals"),
        L("llm", "transformer/ffn", "SwiGLU"),
        L("cpp", "basics/compile-ub", "C++: the compilation model and undefined behavior"), L("cpp", "basics/value-raii", "C++: value semantics and RAII"),
        L("cpp", "basics/move", "C++: move semantics"), L("cpp", "basics/ownership", "C++: smart pointers and ownership"),
        L("torch", "tensor", "PyTorch: tensors, shapes and devices"), L("torch", "autograd", "PyTorch: using autograd"), L("torch", "training", "PyTorch: data and the training loop"),
        E(U.tensorPuzzles, "Tensor Puzzles (warm-up)"), L("scratch", "data", "Training a small model from scratch (corpus, training loop, scaling up)"), L("scratch", "sft", "Instruction tuning: the chat template and loss on the replies only"), L("llm", "training/assignment", "Assignment 1: train a small language model from scratch"), E(U.cs336, "CS336 assignment 1 (for comparison)"), E(U.mlsys, "CMU 15-442 syllabus (to find gaps)")],
      practice: ["llm-stable-softmax", "llm-cross-entropy", "llm-micrograd", "llm-linear-ce-backward", "llm-bf16", "llm-causal-mha", "llm-rope", "llm-rmsnorm", "llm-swiglu",
        "pt-shape-einsum", "pt-mask-gather", "pt-autograd-basics", "pt-module-state", "pt-collate-pad",
        "cpp-raii-fd", "cpp-rule-of-five", "cpp-unique-ptr", "tr-train-loop-bits"],
      algo: "Arrays, hashing, two pointers, sliding windows: 25 problems (with the two algorithm chapters of CS Fundamentals)",
      out: ["Development environment: install every handbook's environment on a Mac in one go (env/setup-macos.sh on the Setup page) and run tools/mac_check.py; sign up for an hourly GPU cloud, and only start machines in the weeks that need a GPU (see the rental list on the Setup page)",
        "Start a technical notes repository (to turn into a blog later); first post: deriving the backward pass of softmax + cross-entropy by hand"],
      check: ["L1 Diagnose yourself with the self-test bank, mark the chapters you do not know and reorder the coming weeks", "L3 Write multi-head attention with a causal mask by hand in 20 minutes (numpy)",
        "L1 Derive the gradient of softmax + cross-entropy and explain why numerical stability means subtracting the maximum", "L1 Explain how fp16, bf16 and fp8 split their bits, and the risks of each", "L2 All of this week's Python exercises pass (judged in the browser), and 3 C++ exercises pass under ASan (judged locally)"] },
    { t: "GPU architecture and CUDA basics + C++ memory", g: "Build a mental model of the GPU: the thread hierarchy, the memory hierarchy, occupancy, warp-level programming.",
      learn: [L("cs", "algo/overview", "CS: preparing for algorithm interviews"), L("cs", "algo/array-string", "CS: arrays and strings"), L("cs", "arch/cpu", "CS: a crash course in CPU architecture"), L("cuda", "basics/gpu-architecture", "GPU architecture"),
        L("cs", "arch/gpu-sm", "CS: the GPU's SMs and Tensor Cores"), L("cs", "arch/gpu-memory", "CS: the GPU memory system"),
        L("cuda", "basics/first-kernel", "Your first CUDA program"), L("cuda", "basics/memory", "The memory hierarchy"),
        L("cuda", "basics/execution", "The execution model"), L("cuda", "basics/sync-warp", "Synchronization and warp programming"),
        L("cpp", "basics/templates", "C++: templates and compile-time dispatch"), L("cpp", "memory/layout", "C++: object layout, alignment and caches"),
        L("cpp", "memory/allocators", "C++: allocators and memory pools"), L("cpp", "basics/stl-perf", "C++: the standard library from a performance angle"),
        L("cpp", "engineering/build-debug", "C++: CMake, sanitizers and perf"),
        E(U.gpuPuzzles, "GPU Puzzles (warm-up)"), E(U.gpumode, "GPU MODE lectures 1–4, 8"), E(U.mamf, "mamf-finder: measure achievable compute")],
      practice: ["alg-two-sum", "alg-max-subarray", "alg-lower-bound", "cu-thread-index", "cu-vector-add", "cu-stencil-smem", "cu-grid-stride", "cu-occupancy", "cu-warp-reduce", "cu-histogram",
        "cs-cache-sets", "cs-pipeline-ilp", "cs-warp-sched", "cs-est-tensor-tile",
        "cpp-dispatch", "cpp-topk", "cpp-arena", "cpp-block-pool", "cpp-struct-layout"],
      algo: "Linked lists, stacks, queues, binary search: 25 problems (with CS: linked lists, stacks and hashing)",
      out: ["The CUDA C++ version of vector addition passes the judge on your own GPU; record its bandwidth as a fraction of peak"],
      check: ["L1 Explain how SMs, warps, thread blocks, shared memory, L2 and HBM relate, and name the H100's key numbers", "L1 Work out a kernel's occupancy by hand and name the limiting resource",
        "L2 Write a warp-shuffle reduction and a histogram with privatized shared memory on a whiteboard", "L2 Explain coalescing and bank conflicts, and confirm them with the emulator's statistics in the exercises",
        "L3 Measure memory bandwidth and achievable compute with python practice/judge.py bench, and keep them as the denominator for every later performance bar"] },
    { t: "Classic kernels and Triton + C++ concurrency", g: "Practice the kernel optimization playbook until it is routine, and learn to argue with a profiler.",
      learn: [L("cuda", "kernels/reduction", "Reduction"), L("cuda", "kernels/transpose", "Transpose"), L("cuda", "kernels/gemm", "The road to a fast GEMM"),
        L("cuda", "kernels/softmax-norm", "Softmax and normalization"), L("cuda", "kernels/scan", "Prefix sums"), L("cuda", "tools/triton", "Triton"), L("cuda", "tools/tilelang", "TileLang"),
        L("cuda", "tools/profiling", "Nsight"),
        L("cpp", "concurrency/threads", "C++: threads, locks and condition variables"), L("cpp", "concurrency/atomics", "C++: atomics and memory order"),
        L("cpp", "concurrency/lockfree-pool", "C++: lock-free queues and thread pools"),
        L("cuda", "framework/tensor", "PyTorch: the memory model of a tensor"), L("cuda", "framework/autograd", "PyTorch: how autograd is implemented"),
        L("cuda", "framework/dispatcher", "PyTorch: the dispatcher and custom operators"),
        E(U.tritonPuzzles, "Triton Puzzles"), E(U.leetcuda, "LeetCUDA: reduction, SGEMM, softmax"), E(U.dlsys, "CMU DLSys needle assignments (optional)")],
      practice: ["cu-est-tile-shmem", "cu-reduction", "cu-transpose-smem", "cu-gemm-tiled", "cu-online-softmax", "cu-block-scan", "cu-triton-softmax", "cu-triton-matmul",
        "cu-est-wave-quant", "cu-est-gemm-traffic", "cu-fusion-traffic", "cpp-bounded-queue", "cpp-spsc-ring", "cpp-thread-pool", "cpp-shared-ptr"],
      algo: "Binary trees, DFS, BFS: 25 problems (with CS: trees and graphs)",
      out: ["A performance report for four kernels on a real GPU (CUDA C++ versions of reduction, transpose, GEMM and softmax), with Nsight Compute analysis"],
      check: ["L3 Write a shared-memory tiled GEMM and online softmax in 45 minutes (CUDA C++)", "L1 Read memory / compute throughput in ncu and say where the gap to the roofline is",
        "L2 Write a fused softmax and a tiled matmul in Triton, and explain how the work divides differently from CUDA", "L2 The C++ blocking queue, SPSC lock-free queue, thread pool and shared_ptr exercises pass under TSan",
        "L3 Real-GPU performance bar: the CUDA C++ reduction and SGEMM both reach the exercises' silver tier (reduction ≥ 80% of measured bandwidth, SGEMM ≥ 70% of cuBLAS)"] },
    { t: "Modern model architectures and how inference works", g: "Master GQA, MLA, MoE, quantization and estimation, as the numerical basis for system design later.",
      learn: [L("llm", "transformer/build-llm", "Assembling an LLM from scratch"), L("llm", "transformer/attention-variants", "MQA / GQA / MLA"), L("llm", "transformer/moe", "MoE"),
        L("llm", "inference/decoding", "Decoding and sampling"), L("llm", "inference/kv-cache", "The KV cache"), L("llm", "inference/estimation", "Estimating parameters and memory"),
        L("llm", "inference/quantization", "How quantization works"), L("llm", "inference/serving", "Inference serving concepts"), L("math", "performance-math", "The math of performance and serving (rooflines, queueing)"),
        L("cs", "arch/evolution", "CS: architecture evolution and the ridge point"),
        E(U.scaling, "Scaling Book: exercises in the roofline, Transformer math and inference chapters"), E(U.efficientml, "MIT 6.5940 quantization lectures (optional)")],
      practice: ["llm-mini-qwen", "llm-gqa", "llm-moe-router", "llm-kv-cache-decode", "llm-param-count", "llm-int4-quant", "llm-roofline", "llm-sampling", "llm-beam-search", "llm-serving-metrics",
        "llm-est-kv-bytes", "llm-est-moe-experts", "llm-est-attn-intensity", "llm-est-decode-bound", "cs-est-arch-gen"],
      algo: "Heaps, greedy, intervals: 20 problems (with CS: sorting, heaps and greedy algorithms)",
      out: ["A one-page estimate: for a 600B-class MLA + MoE model (such as DeepSeek-V3), the weight reads, KV reads, FLOPs and bandwidth bound of one decode step"],
      check: ["L1 Derive MLA by hand: why KV compresses to 512 + 64 dimensions, which matrices absorption merges, and what decode saves", "L1 Explain MoE top-k routing, the load-balancing loss, and auxiliary-loss-free balancing",
        "L3 For any config.json, compute the parameter count, FLOPs per token and KV bytes", "L1 Explain the different bottlenecks of prefill and decode with a roofline, and why batching helps",
        "L3 Solve 80% of the exercises in the Scaling Book's roofline, Transformer math and inference chapters on your own"] },
    { t: "How inference engines work: writing a nano engine from scratch", g: "Implement a paged KV cache, continuous batching, prefix caching, sampling and streaming yourself.",
      learn: [L("serving", "engine/overview", "The life of a request"), L("cs", "os/process-thread", "CS: processes, threads and scheduling"), L("cs", "net/tcp", "CS: TCP and a request's trip through the network"), L("cs", "net/http-stream", "CS: HTTP and streaming output"), L("cs", "algo/linked-stack-hash", "CS: linked lists, stacks and hashing"), L("serving", "engine/paged-kv", "Paged KV cache"), L("cs", "os/virtual-memory", "CS: virtual memory (the prototype of PagedAttention)"), L("serving", "engine/batch-layout", "Variable-length batching"),
        L("serving", "engine/scheduler", "The scheduler"), L("serving", "engine/prefix-cache", "Prefix caching"), L("serving", "engine/sampler-api", "Sampling and the API"),
        L("serving", "engine/graphs-compile", "CUDA Graphs and torch.compile"),
        E(U.nanovllm, "nano-vllm (read alongside)")],
      practice: ["alg-longest-unique", "alg-lru-cache", "alg-monotonic-stack", "alg-block-pool", "sv-block-pool-cow", "sv-batch-layout", "sv-scheduler", "sv-prefix-cache-pool", "sv-stop-strings", "sv-graph-buckets", "cs-cfs-scheduler", "cs-tlb-lru", "cs-est-rtt", "cs-sse-parse"],
      algo: "Backtracking and introductory dynamic programming: 20 problems (with CS: dynamic programming and backtracking; about 115 in total)",
      out: ["Finish the nano engine by following the book, get it running on a GPU and measure its throughput / latency curve"],
      check: ["L1 Explain the trade-offs of continuous batching, chunked prefill and preemption (recompute vs swap)", "L1 Explain how hashed-block and radix-tree prefix caches differ",
        "L1 Explain why CUDA Graph is used only for decode, and the cost of padding",
        "L2 The nano engine's greedy output matches Hugging Face token for token", "Milestone M1 fully reached"] },
    { t: "mini-sglang from scratch (1): computing right, scheduling well", g: "With a real, complete codebase as reference, implement model execution and the scheduler from scratch.",
      learn: [L("minisgl", "overview/architecture", "Guide"), L("minisgl", "overview/tiny-engine", "Step 0: a minimal engine"), L("minisgl", "compute/core", "Core data structures"), L("minisgl", "compute/kvcache", "The KV pool and the page table"),
        L("minisgl", "compute/attention", "Attention backends"), L("minisgl", "compute/engine", "The Engine and sampling"), L("minisgl", "schedule/scheduler", "The scheduler"),
        L("minisgl", "schedule/cache-manager", "CacheManager"), L("minisgl", "schedule/radix-cache", "Radix Cache"), L("minisgl", "schedule/chunked-prefill", "Chunked prefill"),
        L("minisgl", "schedule/overlap", "Overlap scheduling")],
      practice: ["ms-req-lengths", "ms-base-op", "ms-weight-stream", "ms-paged-alloc", "ms-attn-metadata", "ms-batched-sampler", "ms-prefill-adder", "ms-cache-req", "ms-radix-cache", "ms-chunk-size", "ms-overlap-loop"],
      algo: "Dynamic programming: 20 problems",
      out: ["Your own mini-sglang repository: the code of the first 12 chapters with all tests passing (write it yourself first, then compare with the book)"],
      check: ["L1 Without notes, draw the process structure and every message a request goes through", "L1 Explain why admission control reserves for the worst case, and what it costs",
        "L1 Explain the trigger and the fix for each of the four overlap scheduling problems", "L3 Write Radix Cache matching, insertion, locking and eviction within 40 minutes"] },
    { t: "mini-sglang from scratch (2): serving and speed", g: "Turn the engine into a service, add GPU attention backends, CUDA Graph, tensor parallelism and MoE, and write a performance report.",
      learn: [L("minisgl", "wrap/assignment", "Assignment 3: the GPU performance bar for an inference engine"), L("minisgl", "serve/message", "Messages and ZMQ"), L("cs", "os/ipc", "CS: inter-process communication"), L("minisgl", "serve/tokenizer", "Incremental detokenization"), L("cs", "os/io-models", "CS: epoll, asyncio and io_uring"), L("minisgl", "serve/api-server", "API server"),
        L("minisgl", "perf/tensor-parallel", "Tensor parallelism"), L("minisgl", "perf/gpu-attention", "FlashInfer / FlashAttention"), L("minisgl", "perf/cuda-graph", "CUDA Graph"),
        L("minisgl", "perf/kernels", "Custom kernels"), L("minisgl", "perf/moe", "Fused MoE"), L("minisgl", "perf/benchmark", "Benchmarks"), L("cpp", "engineering/python-binding", "C++: pybind11 and PyTorch extensions"),
        L("cuda", "framework/cuda-runtime", "PyTorch's CUDA runtime"), L("cuda", "framework/compiler-basics", "A crash course in compilers"), L("cuda", "framework/compile", "torch.compile"), L("cuda", "framework/compilers", "The AI compiler landscape"),
        E(U.gpumode, "GPU MODE lectures 35 (SGLang performance) and 40 (FlashInfer)")],
      practice: ["cs-broadcast-ring", "cs-event-loop", "ms-message-serde", "ms-incremental-detok", "ms-sse-stream", "ms-shard-tensor", "ms-flashinfer-meta", "ms-graph-replay", "ms-store-kv-kernel", "ms-moe-align"],
      algo: "Graphs, union-find, topological sort: 15 problems",
      out: ["Project A: mini-sglang running Qwen3 on a GPU, with a performance report comparing throughput, TTFT and TPOT against SGLang, and ablations (how much overlap scheduling, CUDA Graph and Radix Cache each contribute)"],
      check: ["L1 Explain why incremental detokenization keeps a context window", "L1 Explain what problem FlashInfer's plan / run split solves",
        "L1 Explain what happens if a CUDA Graph misses copying one input, and how to catch it on CPU", "L3 On the same GPU and load, mini-sglang reaches at least 60% of SGLang's throughput", "L4 You can explain where every number in the performance report comes from"] },
    { t: "SGLang / vLLM source + your first PR", g: "From \"I have written one\" to \"I understand the industrial implementation\", and start showing up in the open-source community.",
      learn: [L("serving", "source/sglang", "SGLang source walkthrough"), L("serving", "source/vllm", "vLLM V1 source walkthrough"), L("cs", "os/io-stack", "CS: how a write reaches the disk (model loading)"), L("minisgl", "wrap/next-steps", "The gap to SGLang"), L("cpp", "engineering/reading-code", "C++: reading the C++ in inference libraries"),
        L("serving", "ops/new-model", "Adding a new model and matching its accuracy (a common first PR)"), L("serving", "source/rust-frontend", "vLLM's Rust frontend (related to project B)")],
      practice: ["sv-first-divergence", "sv-array-struct", "cs-writeback-cache"],
      algo: "Strings, tries, monotonic stacks: 15 problems",
      out: ["Source notes: the call chain from an HTTP request to returned tokens in SGLang (with a diagram), marking the differences from mini-sglang",
        "Your first PR: start with docs, tests or a reproducible small bug (SGLang / vLLM / Mooncake, your choice)"],
      check: ["L3 Find the scheduler, KV allocation, CUDA Graph and model registration in the SGLang source within 5 minutes", "L1 Explain the main differences between vLLM V1 and SGLang in scheduling and prefix caching", "L4 PR submitted"] },
    { t: "Distributed inference and training, communication and storage", g: "Master multi-GPU and multi-node parallelism, communication primitives and KV transfer; be able to explain training-side parallelism too.",
      learn: [L("serving", "distributed/tensor-parallel", "Tensor parallelism"), L("serving", "distributed/expert-parallel", "Expert parallelism and DP attention"), L("serving", "distributed/pp-cp", "Pipeline and context parallelism"),
        L("serving", "distributed/pd-disagg", "PD disaggregation and KV transfer"), L("serving", "distributed/kv-offload", "Tiered KV caching"), L("cuda", "tools/multi-gpu", "Multiple GPUs and NCCL"),
        L("cuda", "tools/streams", "Streams and CUDA Graphs"), L("cuda", "tools/pdl-megakernel", "The gaps between kernels: PDL and megakernels"),
        L("serving", "comm/interconnect", "GPU interconnects and networking"), L("cs", "arch/multi-gpu", "CS: multi-GPU systems and topology"), L("cs", "os/pinned-numa", "CS: pinned memory, DMA and NUMA"), L("serving", "comm/nccl", "NCCL algorithms and custom all-reduce"), L("serving", "comm/rdma", "The RDMA programming model"),
        L("serving", "comm/nvshmem-deepep", "NVSHMEM and DeepEP"), L("serving", "comm/kv-storage", "KV transfer engines and distributed storage"), L("cs", "dist/hash-shard", "CS: consistent hashing and sharding"), L("cs", "algo/tree-graph", "CS: trees and graphs"),
        L("train", "practice/assignment", "Assignment 2: DDP, ZeRO-1 and recomputation"), L("train", "basics/overview", "The memory budget and the time model"), L("train", "basics/collectives", "Collective communication primitives"), L("train", "basics/no-multi-gpu", "Practicing without multiple GPUs"), L("scratch", "one-gpu", "Training a small model on one GPU"), L("train", "data/zero-fsdp", "ZeRO and FSDP"),
        L("train", "model/tensor-sequence", "TP + SP"), L("train", "model/pipeline", "Pipeline parallelism"), L("train", "model/moe-ep", "MoE and expert parallelism"),
        L("train", "practice/strategy", "Combining and choosing parallelism"), L("train", "practice/frameworks-rl", "Frameworks and RL training systems"),
        L("train", "algo/optimizer", "AdamW, Muon and distributed optimizers"), L("train", "algo/stability", "Training stability: QK-Norm, QK-Clip, z-loss, FP4"),
        E(U.playbook, "Ultra-Scale Playbook (read alongside)"), E(U.trainPuzzles, "LLM Training Puzzles"), E(U.allreduce, "all_reduce_bench: measure communication bandwidth"), E(U.cs336, "The DDP and sharded optimizer parts of CS336 assignment 2")],
      practice: ["alg-tree-traverse", "alg-topo-order", "alg-union-find", "alg-trie-prefix", "cs-est-kv-swap", "cs-consistent-hash", "sv-tp-mlp", "sv-ep-dispatch", "sv-ring-attention", "sv-kv-transfer-plan", "sv-kv-offload", "cu-ring-allreduce", "cu-stream-schedule", "cu-trace-analysis",
        "sv-est-tp-comm", "sv-est-ep-a2a", "sv-est-pp-bubble", "sv-est-pd-transfer", "llm-est-train-compute", "llm-est-train-memory",
        "tr-ring-allreduce", "tr-ddp-buckets", "tr-zero-partition", "tr-1f1b-schedule", "sv-allreduce-choice", "tr-muon-step", "tr-qk-clip",
        "tr-device-mesh", "cu-est-decode-gaps", "cs-topo-affinity", "cs-est-mig-split"],
      algo: "Redo the problems you got wrong + 2 timed mocks a week",
      out: ["An estimate: deploying the same MoE model with TP=8 and with EP=8 on an 8-GPU node, comparing the communication volume and time per step"],
      check: ["L1 Explain the communication volume and use cases of all-reduce, all-gather, reduce-scatter and all-to-all", "L1 Explain why DeepEP's high-throughput and low-latency modes are designed the way they are",
        "L1 Explain the benefits and costs of PD disaggregation and the KV transfer options", "L3 Work out the per-GPU memory budget of training a 70B model with ZeRO-3 and with TP + PP",
        "L2 Implement DDP from scratch (gradient bucketing + overlapping communication with computation) and match a single process with multiple processes", "L3 Measure all-reduce bus bandwidth with judge.py bench on a multi-GPU machine and explain the gap to theory", "Milestone M2 fully reached"] },
    { t: "Frontier topic 1: large-scale MoE inference", g: "Read the open inference stack of MLA, FP8, large-scale expert parallelism and MTP closely enough to discuss its details and propose improvements.",
      learn: [L("serving", "moe/mla", "MLA inference: the two computation paths and FlashMLA"), L("serving", "moe/fp8-gemm", "Fine-grained FP8 quantization and DeepGEMM"),
        L("serving", "moe/ep-deploy", "Large-scale EP deployment: hierarchical EPLB and two-batch overlap"), L("serving", "moe/ep-elastic", "Large-scale EP: fault tolerance, elastic scaling and troubleshooting"),
        L("serving", "moe/mtp-sparse", "MTP and sparse attention"),
        L("serving", "moe/case-study", "Case study: published large-scale MoE inference systems"),
        L("serving", "frontier/new-models", "The new generation of open models: compressed attention, hyper-connections and new MoE designs"), L("serving", "frontier/spec-next", "New approaches to speculative decoding"),
        L("llm", "transformer/attention-variants", "MLA revisited"), L("cuda", "advanced/attention", "FlashAttention and inference kernels"), L("cuda", "advanced/async-hopper", "Hopper's asynchronous copies and TMA"), L("cuda", "advanced/cute-layout", "CuTe's layout algebra"),
        L("cuda", "advanced/tensor-core", "Tensor Cores and mma"), L("cuda", "advanced/quantization", "Quantization and GEMV"), L("serving", "topics/speculative", "Speculative decoding in depth"), L("serving", "ops/platforms", "Multi-hardware support: the platform abstraction and the Ascend plugin"),
        E(U.leetcuda, "LeetCUDA: HGEMM, FA2-MMA"), E(U.gpumode, "GPU MODE lectures 36 (CUTLASS and FA3) and 57 (CuTe)"), E(U.efficientml, "MIT 6.5940 AWQ lab (optional)")],
      practice: ["sv-est-mla-paths", "sv-eplb-packing", "cu-flash-attn", "cu-paged-decode", "cu-mma-layout", "cu-async-pipeline", "cu-gemv-int4", "sv-spec-verify", "sv-tree-verify", "sv-est-spec-speedup",
        "sv-est-v4-kv", "sv-adaptive-verify", "sv-expert-coverage", "sv-est-mtp-ep", "cu-cute-layout", "sv-platform-resolve"],
      algo: "2 timed mocks a week",
      out: ["A review of large-scale MoE inference systems: taking the published DeepSeek-V3 inference system as the example, PD disaggregation, EP scale, two-micro-batch overlap and load balancing, each with estimated numbers",
        "Rent a Hopper machine, run the FlashMLA and DeepGEMM benchmarks, and understand their main loops"],
      check: ["L1 Explain what bottleneck FlashMLA removes and how it differs from ordinary paged decode", "L1 Explain the motivation for DeepGEMM's fine-grained FP8 scaling and JIT",
        "L1 Explain how MTP is used for speculative decoding and what DSA's indexer selects", "L1 Answer: if this inference system moved to different hardware, which designs would have to change",
        "L3 Run the official FlashMLA and DeepGEMM benchmarks on Hopper and reproduce at least 80% of the published numbers"] },
    { t: "Frontier topic 2: disaggregation, long context and RL inference", g: "Master the disaggregated architecture centered on the KV cache, and the inference problems of long context and RL.",
      learn: [L("serving", "frontier/disagg-sched", "Global scheduling in disaggregated architectures"), L("serving", "frontier/pd-multiplex", "PD multiplexing: splitting prefill and decode by SM"),
        L("serving", "frontier/linear-attn", "Linear attention and hybrid architectures"),
        L("serving", "frontier/low-bit", "Low-bit inference and QAT"), L("serving", "frontier/rl-async", "Asynchronous RL and weight synchronization"), L("serving", "ops/weight-update", "Hot weight updates"),
        L("serving", "comm/kv-storage", "KV transfer engines and distributed storage"), L("serving", "distributed/pd-disagg", "PD disaggregation revisited"), L("serving", "distributed/kv-offload", "Tiered KV caching"), L("serving", "topics/long-context", "Long context and KV eviction"),
        L("serving", "topics/rl-rollout", "Inference inside RL training"), L("cs", "net/load-balance", "CS: load balancing and queueing"), L("cs", "algo/sort-heap-greedy", "CS: sorting, heaps and greedy algorithms"), L("serving", "topics/deterministic", "Deterministic inference: independent of the batch"), L("train", "practice/frameworks-rl", "Frameworks and RL training systems"), L("train", "algo/rl-algorithms", "RL algorithms in depth: GRPO, DAPO, GSPO, CISPO"), L("serving", "perf/benchmark", "Load testing and SLOs"), L("cs", "os/perf-tools", "CS: Linux performance tools"),
        L("minisgl", "wrap/assignment-hybrid", "Assignment 4 (optional): adding the text part of Qwen3.5 to mini-sglang"),
        E(U.bentoml, "LLM Inference Handbook")],
      practice: ["alg-top-k-heap", "alg-merge-intervals", "alg-task-schedule", "cs-cpu-util", "cs-est-queue", "cs-p2c-balance", "cs-token-bucket", "sv-ttft-router", "sv-est-lowbit-deploy", "sv-cache-aware-router", "sv-kv-block-keys", "sv-kv-eviction", "sv-rollout-sharing", "tr-grpo-advantage", "tr-policy-losses", "tr-qkv-reshard", "sv-memory-plan", "sv-capacity-plan", "sv-step-breakdown", "sv-json-fsm",
        "sv-pdmux-policy", "sv-hot-update", "sv-est-weight-sync", "sv-latency-metrics"],
      algo: "2 timed mocks a week",
      out: ["An analysis of disaggregated inference architectures: the scheduler, KV pool and transfer engine, comparing Mooncake, NVIDIA Dynamo and LMCache",
        "Run a PD disaggregation experiment with Mooncake in SGLang or vLLM (one multi-GPU machine is enough) and record how TTFT / TPOT change"],
      check: ["L1 Explain what objective KV-cache-centric scheduling optimizes and under which constraints", "L1 Explain how sparse attention (NSA, MoBA) and linear attention (the Gated DeltaNet family) each reduce the cost of long context",
        "L1 Explain how RL rollout differs from online serving, and what weight updates need to solve",
        "L4 A PD disaggregation experiment report: how TTFT and TPOT change against no disaggregation, and why"] },
    { t: "Project sprint 1: a Rust inference gateway", g: "Build the project that best shows systems engineering skill, and feed what you learn back to open source.",
      learn: [L("serving", "career/portfolio-guide", "Portfolio guide: design docs and milestones"), L("serving", "engine/prefix-cache", "Cache-aware scheduling and routing"), L("serving", "distributed/pd-disagg", "PD disaggregation"), L("serving", "career/projects", "Portfolio advice")],
      practice: ["sv-cache-aware-router", "sv-capacity-plan"],
      algo: "2 problems a day to stay sharp",
      out: ["Project B: OpenAI compatibility and streaming, cache-aware routing, PD pairing, metrics and a load-test report", "PRs 2 and 3 (preferably to SGLang's Rust gateway or KV transfer projects)"],
      check: ["L4 The load-test report has baselines (round robin, least connections)", "L4 The README gets a stranger running in 10 minutes", "L1 Explain every design trade-off and one failed attempt"] },
    { t: "Project sprint 2: a GPU kernel + technical blog posts", g: "Prove you can work down at the GPU level, and turn the first 12 weeks into public writing.",
      learn: [L("cuda", "advanced/attention", "Inference kernels"), L("cuda", "career/projects", "CUDA portfolio"), L("cuda", "tools/profiling", "Nsight"),
        E(U.kernelbot, "The GPU MODE leaderboard (KernelBot)")],
      practice: [],
      algo: "2 problems a day",
      out: ["Project C: an MLA decode kernel (Triton or CUDA) or a block-scaled FP8 GEMM, with comparison tests and a benchmark",
        "Publish 3 technical blog posts: the mini-sglang performance report, the large-scale MoE inference review, and project B or C", "(Optional) Project D: an inference performance visualization tool"],
      check: ["L3 Project C has numbers for its fraction of peak, and ncu explains the remaining gap",
        "L3 (optional) Submit a problem to the GPU MODE leaderboard and record your rank", "Milestone M3 fully reached"] },
    { t: "System design + résumé + practice interviews", g: "Shape your knowledge into what interviews can use.",
      learn: [L("serving", "career/system-design", "System design questions"), L("serving", "career/design-answers-1", "System design reference answers (1)"), L("serving", "career/design-answers-2", "System design reference answers (2)"), L("serving", "career/mock-exams", "Mock interview sets"),
        L("serving", "k8s/basics", "K8s core objects and the controller pattern"), L("serving", "k8s/scheduling", "The K8s scheduler and GPU scheduling"), L("serving", "k8s/gpu", "How K8s manages GPUs"), L("serving", "k8s/deploy-scale", "Deploying and scaling on K8s"), L("serving", "k8s/multi-node", "Multi-node, multi-GPU and disaggregated deployment on K8s"), L("serving", "k8s/operator-ops", "K8s operators, quotas and troubleshooting"), L("serving", "ops/deploy", "Production deployment and operations"), L("cs", "os/containers", "CS: containers and cgroups"), L("cs", "dist/replication", "CS: replication and consensus"), L("cs", "algo/dp-backtrack", "CS: dynamic programming and backtracking"), L("serving", "ops/frameworks", "Choosing an inference framework"), L("serving", "career/interview", "Interview questions for inference roles"), L("serving", "career/projects", "Portfolio and résumé"), L("serving", "career/mock-interview", "Mock interviews: rubric and review"),
        E(U.zomi, "ZOMI AIInfra: containers and cloud native"), E(U.bentoml, "LLM Inference Handbook: deployment and operations")],
      practice: ["sv-k8s-reconcile", "sv-k8s-scheduler", "sv-est-rollout", "sv-k8s-probe", "sv-k8s-gang", "sv-k8s-quota", "sv-est-mig-share", "alg-coin-change", "alg-edit-distance", "alg-backtrack-subsets", "sv-est-cluster-size", "sv-capacity-plan", "sv-memory-plan", "sv-est-rolling-update", "cs-cpu-quota", "cs-quorum-vote"],
      algo: "3 timed mocks a week",
      out: ["Answers to the 10 system design questions (architecture diagrams + estimates)", "A final one-page résumé, every project in three parts: problem → solution → numbers", "Apply to 2–3 similar roles for practice"],
      check: ["L3 Finish each system design question within 45 minutes, with capacity estimates", "L4 Have someone run 2 mock interviews with you, and review them"] },
    { t: "Fundamentals and follow-ups sprint + the first real interviews", g: "Hone every topic into \"a one-sentence answer that holds up under follow-ups\".",
      learn: [L("serving", "career/interview", "Interview questions for inference roles"), L("llm", "synthesis/quiz", "The LLM self-test bank"), L("cuda", "career/interview", "CUDA interview questions"), L("cpp", "engineering/interview", "Frequent C++ interview questions"),
        L("serving", "career/hardware", "Hardware and ecosystem cheat sheet"), L("serving", "career/mock-interview", "Mock interview rubric"),
        E(U.aig, "AIInfraGuide interview guide (mock questions by topic)")],
      practice: [],
      algo: "The problems you got wrong in the second pass of Hot 100",
      out: ["Interview flashcards: a one-sentence answer plus one follow-up per topic, about 150 cards", "The first real applications (referrals first)"],
      check: ["L4 At least 2 mock interviews, scoring at least 3 on all four rubric criteria", "L4 Write a review within 24 hours of every real interview and fill in what you answered poorly"] },
    { t: "The second round of real interviews", g: "Interview for the roles you want most when you are at your best.",
      learn: [L("serving", "distributed/expert-parallel", "Expert parallelism revisited"), L("llm", "transformer/moe", "MoE revisited"), L("cuda", "advanced/attention", "Inference kernels revisited")],
      practice: ["llm-causal-mha", "llm-sampling", "ms-radix-cache", "py-blocking-queue", "cu-gemm-tiled"],
      algo: "2 problems a day + rotate through the hand-written components",
      out: ["The second round of applications (referrals first)", "For each job description, prepare 10 likely follow-up questions and answers for each relevant paper"],
      check: ["L3 One timed pass of hand-writing: attention, top-p sampling, Radix Cache, a thread pool, a tiled GEMM", "L1 For every project, prepare 3 hard parts, 3 numbers and 1 failed attempt"] },
    { t: "Buffer, review and decision", g: "Handle extra and follow-up interviews, and make your choice.",
      learn: [L("serving", "career/projects", "Study plan and portfolio")],
      practice: [],
      algo: "Shore up weak spots from interview feedback",
      out: ["Prepare for extra / follow-up interviews", "Compare offers: team direction (inference systems, training infrastructure, storage and networking) and room to grow"],
      check: ["L4 Turn 17 weeks of notes and projects into a personal home page you can keep maintaining"] },
  ];

  var MILESTONES = [
    { c: "c-blue", when: "End of week 5", t: "M1 Foundations done", items: ["≥ 80% of the Python, LLM and CUDA exercises passed", "GQA attention with a KV cache plus RoPE on a whiteboard in 30 minutes",
      "A warp reduction and a tiled GEMM in 45 minutes (CUDA C++)", "About 115 algorithm problems; medium ones solved within 25 minutes at least 70% of the time", "Explain the bottlenecks of prefill and decode in numbers", "Real GPU: reduction ≥ 80% of measured bandwidth, SGEMM ≥ 70% of cuBLAS; estimation questions within 10%"] },
    { c: "c-green", when: "End of week 9", t: "M2 Engine done", items: ["Your mini-sglang runs on a GPU and the performance report is done", "≥ 80% of the inference systems and mini-sglang exercises passed",
      "Draw SGLang's whole flow and explain each design trade-off", "First PR submitted",
      "mini-sglang throughput ≥ 60% of SGLang on the same GPU and load; a from-scratch DDP matches a single process"] },
    { c: "c-orange", when: "End of week 13", t: "M3 Portfolio done", items: ["Projects B and C done, 3 technical blog posts published", "At least 3 PRs, at least 1 merged",
      "Talk for 15 minutes without notes on each of two frontier-topic reviews", "Once you are here you can start applying; no need to wait for week 15"] },
    { c: "c-pink", when: "Week 16", t: "M4 Interview ready", items: ["About 200 algorithm problems; Hot 100 done twice", "10 system design questions and at least 6 mock interviews",
      "About 150 flashcards, and the whole reading list read closely", "Every project holds up under 30 minutes of follow-up questions", "Your last 3 mock interviews score at least 3 on all four criteria"] },
  ];

  var PROJECTS = [
    { c: "c-green", t: "Project A · a full mini-sglang rebuild", why: "Required (weeks 6–7). Proves you understand every part of an inference engine.", pass: [
      "Implement it from scratch following the book (write it yourself first, then compare), run Qwen3 on a GPU with output matching Hugging Face token for token",
      "Compare throughput, TTFT and TPOT with SGLang; ablate how much overlap scheduling, CUDA Graph, Radix Cache and chunked prefill each contribute",
      "Deliverables: a code repository + a performance report + a blog post"], links: [L("minisgl", "overview/architecture", "mini-sglang from scratch"), L("minisgl", "perf/benchmark", "Benchmarks and ablations")] },
    { c: "c-orange", t: "Project B · a PD-aware Rust inference gateway", why: "Stands out (week 12). Shows systems engineering and Rust, and connects directly to real inference frameworks.", pass: [
      "An OpenAI-compatible API with SSE streaming; cache-aware routing (an approximate prefix tree) + load balancing",
      "Pairing prefill / decode instances and coordinating KV transfer (working with SGLang's PD disaggregation); health checks, circuit breaking, retries; Prometheus metrics",
      "Load tests: TTFT, throughput and cache hit rate against round robin and least connections; fault-injection tests",
      "Bonus: contribute the ideas or code to SGLang's Rust gateway"], links: [L("serving", "career/portfolio-guide", "Portfolio guide"), L("serving", "engine/prefix-cache", "Cache-aware routing"), L("serving", "distributed/pd-disagg", "PD disaggregation"), ["practice", "sv-cache-aware-router", "Exercise: cache-aware routing"]] },
    { c: "c-purple", t: "Project C · a GPU kernel", why: "Depth (week 13). Proves you can work down at the GPU level rather than only call libraries.", pass: [
      "Pick one: an MLA decode kernel (following FlashMLA's ideas, Triton first, then CUDA), or a block-scaled FP8 GEMM (following DeepGEMM)",
      "Compare against a reference implementation; report bandwidth or TFLOPS as a fraction of peak on Hopper",
      "Explain the remaining gap and the next optimization with Nsight Compute"], links: [L("serving", "career/portfolio-guide", "Portfolio guide"), L("cuda", "advanced/attention", "Inference kernels"), L("cuda", "advanced/async-hopper", "Hopper asynchronous copies"), L("cuda", "career/projects", "CUDA portfolio")] },
    { c: "c-teal", t: "Project D · an inference performance visualization tool (optional)", why: "A bonus. Turns tooling skill into something you can demo live in an interview.", pass: [
      "Turn torch profiler traces and engine logs into an interactive timeline: the batch composition of each step, KV usage, CPU / GPU idle time, and the breakdown of each request's TTFT",
      "Load SGLang / vLLM logs and traces directly and diagnose automatically (for example, too much CPU overhead or CUDA Graph misses)",
      "Deliverables: an online demo + a case study of using it to find a real performance problem"], links: [L("serving", "career/portfolio-guide", "Portfolio guide"), L("serving", "perf/profiling", "Profiling an inference engine"), ["practice", "cu-trace-analysis", "Exercise: timeline analysis"]] },
    { c: "c-pink", t: "Open-source contributions (weeks 8–16)", why: "Interviewers can read your code directly, which is more convincing than any description.", pass: [
      "Aim for 3–5 PRs, at least 1–2 of them substantive changes beyond docs",
      "The path: docs and tests → reproduce and fix bugs → small features; put the reproduction steps, tests and benchmark data in the PR description",
      "Watch the issues of SGLang (including the Rust gateway), vLLM, FlashInfer, Mooncake and similar projects"], links: [L("serving", "source/sglang", "SGLang source walkthrough"), L("serving", "source/vllm", "vLLM source walkthrough")] },
  ];

  var ALGO = ["Week 1: arrays, hashing, two pointers, sliding windows (25)", "Week 2: linked lists, stacks, queues, binary search (25)", "Week 3: binary trees, DFS / BFS (25)",
    "Week 4: heaps, greedy, intervals (20)", "Week 5: backtracking, introductory dynamic programming (20)", "Week 6: dynamic programming (20)", "Week 7: graphs, union-find, topological sort (15)",
    "Week 8: strings, tries, monotonic stacks (15)", "Weeks 9–13: 2 timed mocks a week + redo wrong answers (about 35)", "Weeks 14–16: a second pass over the Hot 100 problems you got wrong; 2 problems a day before interviews to stay sharp"];
  var HANDWRITE = [
    ["Numerically stable softmax / logsumexp", "llm-stable-softmax"], ["Multi-head / GQA attention with a causal mask + KV cache", "llm-kv-cache-decode"], ["RoPE", "llm-rope"],
    ["RMSNorm / LayerNorm", "llm-rmsnorm"], ["temperature / top-k / top-p sampling", "llm-sampling"], ["Beam search", "llm-beam-search"], ["BPE training and encoding", "llm-bpe"],
    ["LRU cache", "py-lru-cache"], ["Radix Cache", "ms-radix-cache"], ["Paged KV block allocator (reference counting, copy-on-write)", "sv-block-pool-cow"],
    ["Continuous batching scheduler", "sv-scheduler"], ["MoE routing and dispatch", "llm-moe-router"], ["Speculative decoding verification", "sv-spec-verify"], ["Blocking queue / thread pool", "py-blocking-queue"],
    ["Lock-free single-producer single-consumer queue (C++)", "cpp-spsc-ring"], ["Thread pool (C++, futures and exception propagation)", "cpp-thread-pool"], ["CUDA: reduction, transpose, tiled GEMM", "cu-gemm-tiled"], ["online softmax (CUDA / Triton)", "cu-online-softmax"],
    ["FlashAttention forward (tiled)", "cu-flash-attn"], ["ring all-reduce", "cu-ring-allreduce"], ["Dynamic batcher (asyncio)", "py-dynamic-batcher"],
    ["Intrusive reference counting (C++, memory order)", "cpp-refcount"], ["GPU memory caching allocator (best fit, splitting and merging)", "cu-caching-allocator"]];
  var DESIGN = ["An online inference service for a 600B-class MoE model: PD disaggregation + large-scale EP, with machine count, throughput and latency",
    "A multi-tier cache pool centered on the KV cache: GPU / CPU / SSD tiers, cross-machine transfer, eviction and consistency",
    "An inference gateway with global, cache-aware scheduling: routing policy, load balancing, failover, canary releases",
    "A multi-tenant LoRA service: loading and swapping adapters, batching, isolation and billing",
    "An RL rollout system: training and inference sharing a cluster, weight synchronization, long-tail requests, elasticity",
    "A million-token long-context service: context parallelism, sparse attention, KV offloading, time to first token",
    "Speculative decoding as a service: deploying draft models, monitoring acceptance rates, interaction with batching",
    "A structured output and tool-calling service: the cost of constrained decoding, streaming parsing, timeouts and retries",
    "Inference observability and autoscaling: metrics, SLOs, capacity forecasting, cold starts",
    "A multi-region, multi-cluster inference platform: traffic scheduling, model distribution, disaster recovery and cost optimization"];
  var PAPERS = [
    "★ Orca: iteration-level scheduling (OSDI'22)", "★ vLLM: PagedAttention (SOSP'23)", "★ SGLang: RadixAttention (NeurIPS'24)",
    "★ Sarathi-Serve: chunked prefill (OSDI'24)", "★ DistServe / Splitwise: PD disaggregation (OSDI'24 / ISCA'24)", "★ FlashAttention 1 / 2 / 3",
    "★ The DeepSeek-V2 / V3 technical reports (MLA, MoE, MTP, FP8)", "★ Mooncake: a disaggregated architecture centered on the KV cache (FAST'25)", "★ Megatron-LM and ZeRO: training-side parallelism and memory",
    "FlashInfer (MLSys'25)", "Overview of the DeepSeek open inference system, and FlashMLA, DeepEP, DeepGEMM", "Insights into DeepSeek-V3 (ISCA'25, hardware and model co-design)",
    "The design docs of NVIDIA Dynamo, LMCache and llm-d", "Sparse and linear attention: NSA, MoBA, Gated DeltaNet", "Medusa and EAGLE 1 / 2 / 3: speculative decoding",
    "SmoothQuant, AWQ, GPTQ: quantization", "GShard / Switch Transformer: MoE and expert parallelism", "DeepSeek-R1 and GRPO: reasoning models and RL",
    "HybridFlow (verl): inference inside an RL training framework"];
  var TIMELINE = ["From week 8: leave searchable traces in open-source communities and on your blog; collect referral channels (colleagues, communities, technical groups)",
    "Weeks 13–14: apply to 2–3 similar roles for practice and get used to the interview rhythm", "Week 15: the first real applications (referrals first); use the results to adjust the focus of the last two weeks",
    "Week 16: the second round of real applications; put the roles you want most when you are at your best", "Review within 24 hours of each interview: what was asked, how you answered, what to fill in",
    "If the hiring window is uncertain, go by \"apply once M3 is reached\""];
  var RESUME = ["One page; put your target direction (inference systems / AI infrastructure), projects and open-source contributions on the first screen, then past experience",
    "Every project in three parts: problem (why it is hard) → solution (the key design) → numbers (throughput, latency, cost, scale)",
    "Restate past experience in the language of inference systems: scheduling, memory and caching, asynchronous execution, network transfer, observability, stability",
    "Prepare 3 stories, each with numbers: a performance optimization, a complex system design, a production incident investigation",
    "Put links to GitHub, the blog, project demos and PRs directly in the résumé"];
  var RHYTHM = [["c-blue", "7 h", "Algorithms: 1 hour every weekday (about 2 problems)"], ["c-green", "14 h", "Main study: chapters + exercises + checklists"],
    ["c-orange", "6 h", "Projects / open source: concentrated on weekends"], ["c-purple", "3 h", "Writing and review: weekly notes, blog, flashcards; tick the checklist on Sundays"]];
  var BUILD = [
    { c: "c-indigo", t: "P0 · The Advanced C++ handbook (done)", why: "15 chapters + 11 C++ exercises judged locally (ASan / UBSan / TSan). For weeks 1–3.", pass: [
      "Modern C++ essentials: value semantics, RAII, move, smart pointers, templates and constexpr", "Memory: object layout, alignment, allocators and memory pools",
      "Concurrency: threads, atomics, memory order, lock-free queues, thread pools and coroutines", "Engineering: CMake, testing, sanitizers, perf; pybind11 and PyTorch C++ extensions; how to read open-source infrastructure libraries"] },
    { c: "c-orange", t: "P0 · Tools to verify results (done)", why: "For the whole plan. Turns \"I feel I know it\" into numbers you can check.", pass: [
      "✓ Estimation questions (20, live): training compute and MFU, training memory, the KV budget, MoE expert reads, attention arithmetic intensity, decode / prefill bounds, GEMM waves and traffic, TP / EP communication, PD transfer, pipeline bubbles, speculative decoding, deployment size",
      "✓ Real-GPU performance tiers (live): CUDA C++ exercises are graded bronze, silver or gold on a GPU against this machine's measured bandwidth or cuBLAS on the same shape",
      "✓ Local benchmark script (live): judge.py bench measures memory bandwidth, achievable compute and multi-GPU all-reduce bus bandwidth",
      "✓ Mock interview rubric and review template (live): the \"Mock interviews\" chapter of the inference systems book"] },
    { c: "c-green", t: "P0 · The Distributed Training handbook (done)", why: "11 chapters. Every kind of parallelism is implemented from scratch and matched item by item (forward, loss, gradients) against a single process with multiple CPU processes. For week 9, and it supports RL inference.", pass: [
      "Overview and the memory budget: parameters, gradients, optimizer state, activations", "Collective communication primitives and NCCL; DP / DDP; ZeRO 1 / 2 / 3 and FSDP",
      "Megatron TP + SP, PP schedules (1F1B, interleaved, zero bubble), CP and long-sequence training, MoE and EP", "Mixed precision and FP8 training, recomputation and offloading; choosing a 3D parallelism strategy; Megatron-LM, DeepSpeed, torchtitan, verl in practice",
      "Verified the same way as the inference systems book: multiple CPU processes match a single process numerically, and memory budgets are compared with measurements"] },
    { c: "c-teal", t: "P0 · Communication and storage (done)", why: "5 new chapters on communication and storage in the inference systems book; the α-β model and the routing and caching simulations are all run and verified. For week 9.", pass: [
      "RDMA and GPUDirect RDMA, NVLink / NVSwitch and NCCL's algorithms", "How NVSHMEM and DeepEP are implemented", "KV transfer engines and KV cache storage (Mooncake Transfer Engine, 3FS)"] },
    { c: "c-blue", t: "P1 · Frontier topic: large-scale MoE inference (done)", why: "5 new chapters in the inference systems book; MLA equivalence, FP8 error, EPLB, the cost of MTP / DSA and the checks against published systems are all run and verified. For week 10.", pass: [
      "MLA and FlashMLA", "Fine-grained FP8 quantization and DeepGEMM", "DeepEP and large-scale expert parallelism, EPLB", "MTP and sparse attention (NSA, DSA)", "Reviewing and estimating open inference systems"] },
    { c: "c-purple", t: "P1 · Frontier topic: disaggregation, long context and RL inference (done)", why: "4 new chapters in the inference systems book; the routing, ratio, linear attention, QAT and asynchronous RL simulations are all run and verified. For week 11.", pass: [
      "KV-centric disaggregated architectures: comparing Mooncake, NVIDIA Dynamo and LMCache", "Implementing sparse and linear attention for inference", "Low-bit inference for very large MoE models: INT4 QAT, FP4", "RL rollout, weight synchronization and unified training and inference"] },
    { c: "c-orange", t: "P1 · PyTorch internals and AI compilers (done)", why: "6 new chapters on frameworks and compilers in the CUDA book. For weeks 3 and 7.", pass: [
      "Tensors, strides and views; the autograd engine; the dispatcher and custom operators; the CUDA caching allocator", "torch.distributed and torchrun",
      "Graph optimization and operator fusion; torch.compile (Dynamo + Inductor); the ideas of TVM / MLIR / XLA; TileLang and the CuTe DSL"] },
    { c: "c-teal", t: "P1 · Assignments (minimal scaffolding, done)", why: "The repository's assignments/ directory: only interfaces, tests and grading scripts, no skeleton; reference solutions are not public, and the tests are checked against them. For weeks 1 and 9.", pass: [
      "Train a small model from scratch: BPE, the Transformer, AdamW and the training loop, getting validation loss to a target within a time limit",
      "A training system: DDP + ZeRO-1 + activation recomputation, measuring throughput and memory against estimates",
      "An inference engine: continuing the hand-written mini-sglang with a performance bar on a GPU",
      "A hybrid architecture: add the text part of Qwen3.5 (Gated DeltaNet + gated attention, a per-request state pool) to mini-sglang, matching transformers token for token"] },
    { c: "c-red", t: "P1 · Portfolio guide (done)", why: "The \"Portfolio guide\" chapter of the inference systems book. For weeks 8, 12 and 13.", pass: [
      "Design doc templates, milestones and acceptance metrics for projects B, C and D", "Getting started with open source: code tours of each project, picking issues, writing PRs"] },
    { c: "c-pink", t: "P2 · More interview questions (done)", why: "For weeks 14–16.", pass: [
      "✓ Full reference answers to the 10 system design questions (architecture diagrams + runnable estimates): \"System design reference answers (1) and (2)\" in the inference systems book", "✓ All 23 hand-written components have exercises (including the C++ lock-free queue, thread pool and reference counting, and the GPU caching allocator)",
      "✓ Mock interview sets: four sets built like real interviews (coding + follow-ups + system design + projects; the fourth leans toward large-scale MoE and RL inference), with key points and chapter links", "✓ Follow-up lists: the 85 questions of the inference interview bank, organized by topic; the algorithm list is under interview prep on this page (\"Algorithms: about 200 problems, week by week\")"] },
    { c: "c-indigo", t: "P2 · Additions to the inference systems book (done)", why: "4 new chapters on production and the ecosystem in the inference systems book, and \"Pruning, 2:4 sparsity and distillation\" in the LLM book. For week 14.", pass: [
      "Production deployment and operations: inference services on Kubernetes, faster model loading, autoscaling, canary releases and observability", "Choosing an inference framework: the trade-offs of vLLM, SGLang, TensorRT-LLM and LMDeploy",
      "Multi-LoRA serving", "On-device inference: llama.cpp and GGUF, MLX, ExecuTorch", "Pruning, 2:4 sparsity and distillation (an extension of the LLM book's quantization chapter)"] },
  ];

  return {
    BOOK: BOOK, U: U, ABILITIES: ABILITIES, DIRS: DIRS, LEVELS: LEVELS, TOOLBOX: TOOLBOX,
    REFS: REFS, EDGE: EDGE, PHASES: PHASES, WEEKS: WEEKS, MILESTONES: MILESTONES, PROJECTS: PROJECTS,
    ALGO: ALGO, HANDWRITE: HANDWRITE, DESIGN: DESIGN, PAPERS: PAPERS, TIMELINE: TIMELINE, RESUME: RESUME,
    RHYTHM: RHYTHM, BUILD: BUILD
  };
})();
