"""MkDocs hook: inline the generated SVG figures so their text and lines follow the light / dark theme.

In Markdown a figure is an image line with the `.aig-svg` class:

    ![图：一个 decoder 层](../assets/figures/decoder-block.svg){.aig-svg}

The SVG files are generated by tools/figures.py; they draw text and strokes with `currentColor` and fill shapes
with CSS classes (theme/assets/stylesheets/aig.css), which only works when the SVG is inline in the page. The
image path is resolved relative to the Markdown file, and the alt text becomes the caption.
"""

import re
from pathlib import Path

_FIG = re.compile(r"^!\[([^\]]*)\]\(([^)]+\.svg)\)\{\s*\.aig-svg\s*\}[ \t]*$")
_FENCE = re.compile(r"^\s*(```+|~~~+)")


def on_page_markdown(markdown, page, config, files):
    src = Path(page.file.abs_src_path).parent
    out, fence = [], None
    for line in markdown.split("\n"):
        f = _FENCE.match(line)
        if f and (fence is None or f.group(1)[0] == fence[0] and len(f.group(1)) >= len(fence)):
            fence = f.group(1) if fence is None else None     # a figure line inside a code block stays as it is
        m = _FIG.match(line) if fence is None else None
        if m:
            caption, rel = m.groups()
            svg = (src / rel).read_text(encoding="utf-8").strip()
            svg = re.sub(r"^<\?xml[^>]*\?>\s*", "", svg)
            cap = f"<figcaption>{caption}</figcaption>" if caption else ""
            line = f'<figure class="aig-fig" markdown="0">{svg}{cap}</figure>'
        out.append(line)
    return "\n".join(out)
