"""Extract, compile and (where possible) run the code examples embedded in docs/.

Conventions in the Markdown:
  ```cuda title="name.cu"    complete program; its first lines contain the nvcc command
  ```cuda title="name.cuh"   shared header, written next to the programs
  ```python title="name.py"  Triton / PyTorch script, run with TRITON_INTERPRET=1 on CPU
  blocks without a title are illustrative snippets and are not checked

Every .cu file is compiled with each toolkit in TOOLKITS. No GPU is needed.
The extracted files, a Makefile and a README are packed into docs/assets/cuda-examples.tar.gz
so readers can build and run everything on a real GPU with `make run`.

Usage: python tools/check_code.py [docs/page.md ...]   (no args: every page, and rebuild the pack)
"""

import os
import re
import shlex
import subprocess
import sys
import tarfile
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.environ.setdefault("CUTLASS_DIR", str(ROOT / ".cutlass"))
BUILD = ROOT / "build" / "examples"
TOOLKITS = {
    "cuda-13.4": ROOT / ".toolkit" / "bin" / "nvcc",
    "cuda-12.9": ROOT / ".toolkit12" / "bin" / "nvcc",
}
TRITON_PY = ROOT / ".venv-triton" / "bin" / "python"
FENCE = re.compile(r"^(?P<indent>[ \t]*)(?P<fence>`{3,}|~{3,})(?P<lang>[\w+-]*)(?P<rest>.*)$")
TITLE = re.compile(r'title="([^"]+)"')


def blocks(md: Path):
    lines = md.read_text(encoding="utf-8").splitlines()
    i = 0
    while i < len(lines):
        m = FENCE.match(lines[i])
        if not m:
            i += 1
            continue
        indent, fence = m["indent"], m["fence"]
        j = i + 1
        while j < len(lines):
            s = lines[j].strip()
            if s.startswith(fence) and set(s) == {fence[0]}:
                break
            j += 1
        body = [ln[len(indent):] if ln.startswith(indent) else ln.lstrip() for ln in lines[i + 1:j]]
        t = TITLE.search(m["rest"])
        if t:
            yield t.group(1), i + 2, "\n".join(body) + "\n"
        i = j + 1


def nvcc_flags(code: str, name: str):
    """Flags from the first comment line that mentions nvcc, minus the source file and -o target."""
    if "#include <torch/extension.h>" in code:
        return ["<torch-extension>"]
    for line in code.splitlines()[:6]:
        if "nvcc" in line:
            args = shlex.split(line[line.index("nvcc") + 4:])
            out, skip = [], False
            for a in args:
                if skip:
                    skip = False
                    continue
                if a == "-o":
                    skip = True
                    continue
                if a.endswith(".cu"):
                    continue
                out.append(a)
            return out
    raise ValueError(f"{name}: no '// ... nvcc ...' build line in the first lines")


def torch_ext_flags():
    """Compile-only flags for PyTorch extension sources, using the CPU torch wheel's headers."""
    code = ("import torch, os, sysconfig; t = os.path.dirname(torch.__file__); "
            "print(t + '/include'); print(t + '/include/torch/csrc/api/include'); print(sysconfig.get_paths()['include'])")
    inc = subprocess.run([str(TRITON_PY), "-c", code], capture_output=True, text=True, check=True).stdout.split()
    stub = ROOT / "tools" / "torch_stub"   # c10/cuda/impl/cuda_cmake_macros.h is only generated for CUDA wheels
    return ["-O3", "-arch=sm_80", "-c", "-std=c++20", "-DTORCH_EXTENSION_NAME=handbook_ops",
            *[f"-I{d}" for d in inc], f"-I{stub}"]


def compile_one(name, flags):
    results = []
    for label, nvcc in TOOLKITS.items():
        exe = BUILD / "bin" / label / Path(name).stem
        exe.parent.mkdir(parents=True, exist_ok=True)
        if flags == ["<torch-extension>"]:
            cmd = [str(nvcc), *torch_ext_flags(), str(BUILD / name), "-o", str(exe) + ".o"]
        else:
            cmd = [str(nvcc), *[os.path.expandvars(f) for f in flags], "-std=c++17", str(BUILD / name), "-o", str(exe)]
        p = subprocess.run(cmd, capture_output=True, text=True, cwd=BUILD)
        warn = [ln for ln in (p.stderr or "").splitlines() if "warning" in ln.lower()]
        results.append((label, p.returncode, p.stderr.strip(), warn))
    return name, results


def run_python(name):
    env = {**os.environ, "TRITON_INTERPRET": "1"}
    p = subprocess.run([str(TRITON_PY), name], capture_output=True, text=True, cwd=BUILD, env=env, timeout=900)
    return name, p.returncode, (p.stdout + p.stderr).strip()


def write_pack(cu_files):
    cu_files = [(n, f) for n, f in cu_files if f != ["<torch-extension>"]]   # built by setup.py, not make
    optional = [n for n, f in cu_files if "-lnccl" in f or any("CUTLASS_DIR" in x for x in f)]
    lines = [
        "# Generated by tools/check_code.py. Build and run every example on a machine with an NVIDIA GPU.",
        "NVCC ?= nvcc",
        "NVCC_EXTRA ?=",
        f"BINS := {' '.join(Path(n).stem for n, _ in cu_files if n not in optional)}",
        f"EXTRA := {' '.join(Path(n).stem for n in optional)}",
        "",
        "all: $(BINS)",
        "",
        "extra: $(EXTRA)   # examples that need NCCL (and 2+ GPUs) or CUTLASS (set CUTLASS_DIR)",
        "",
    ]
    for name, flags in cu_files:
        lines.append(f"{Path(name).stem}: {name} common.cuh")
        lines.append(f"\t$(NVCC) {' '.join(flags)} -std=c++17 $(NVCC_EXTRA) {name} -o $@")
        lines.append("")
    lines += [
        "run: all",
        '\t@for b in $(BINS); do echo "=== $$b"; ./$$b || echo "!!! $$b exited with an error"; done',
        "",
        "clean:",
        "\trm -f $(BINS) $(EXTRA)",
        "",
        ".PHONY: all extra run clean",
    ]
    (BUILD / "Makefile").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (BUILD / "README.md").write_text(
        "# CUDA 学习手册示例代码\n\n"
        "每个 .cu 文件都是一个独立程序，开头注释里写了编译命令和最低 GPU 架构要求。\n\n"
        "```bash\nmake -j8        # 编译全部\nmake run        # 逐个运行，看每个程序输出的 PASS / FAIL / SKIP\n"
        "make gemm       # 只编译某一个\nmake extra      # 多 GPU 示例（需要 NCCL 和至少 2 张卡）\n```\n\n"
        "算力不够的 GPU 上，需要更高架构的程序会打印 SKIP 并跳过。*.py 是 Triton 示例，需要 `pip install torch triton`。\n",
        encoding="utf-8",
    )
    out = ROOT / "docs" / "assets" / "cuda-examples.tar.gz"
    out.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(out, "w:gz") as tar:
        for f in sorted(BUILD.iterdir()):
            if f.is_file():
                tar.add(f, arcname=f"cuda-examples/{f.name}")
    print(f"packed {out.relative_to(ROOT)}")


def main(argv):
    pages = [Path(p).resolve() for p in argv] or sorted((ROOT / "docs").rglob("*.md"))
    full_run = not argv
    BUILD.mkdir(parents=True, exist_ok=True)

    seen, cu_files, py_files = {}, [], []
    # headers first: programs from any page may include them
    for md in sorted((ROOT / "docs").rglob("*.md")):
        for name, lineno, code in blocks(md):
            if name.endswith((".cuh", ".h")):
                (BUILD / name).write_text(code, encoding="utf-8")
    for md in pages:
        for name, lineno, code in blocks(md):
            where = f"{md.relative_to(ROOT)}:{lineno}"
            if name in seen and seen[name] != where:
                raise SystemExit(f"duplicate file name {name}: {seen[name]} and {where}")
            seen[name] = where
            (BUILD / name).write_text(code, encoding="utf-8")
            if name.endswith(".cu"):
                cu_files.append((name, nvcc_flags(code, name)))
            elif name.endswith(".py"):
                py_files.append(name)

    failed = 0
    with ThreadPoolExecutor(max_workers=8) as pool:
        for name, results in pool.map(lambda nf: compile_one(*nf), cu_files):
            for label, rc, err, warn in results:
                status = "ok" if rc == 0 else "FAIL"
                extra = f" ({len(warn)} warnings)" if warn else ""
                print(f"[{status}] {label:10s} {name}{extra}")
                if rc != 0 or warn:
                    print("    " + err.replace("\n", "\n    ")[:3000])
                failed += rc != 0
    for name in py_files:
        name, rc, out = run_python(name)
        print(f"[{'ok' if rc == 0 else 'FAIL'}] triton-cpu {name}")
        print("    " + out.replace("\n", "\n    ")[-1500:])
        failed += rc != 0

    if full_run and not failed:
        all_cu = []
        for md in sorted((ROOT / "docs").rglob("*.md")):
            for name, _, code in blocks(md):
                if name.endswith(".cu"):
                    all_cu.append((name, nvcc_flags(code, name)))
        write_pack(all_cu)
    print(f"\n{len(cu_files)} CUDA programs x {len(TOOLKITS)} toolkits, {len(py_files)} Python scripts, {failed} failures")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
