// 冲刺计划的数据：计划页（plan.js）渲染它，学习路线图（../roadmap/）也从这里读每周的目标、验收和产出，保证两边一致。
window.AIG_PLAN = (function () {
  "use strict";

  var BOOK = { python: "Python", cpp: "C++", llm: "大模型", cuda: "CUDA", train: "分布式训练", serving: "推理系统", minisgl: "mini-sglang" };
  function L(book, path, title) { return [book, path, title]; }
  function E(url, title) { return ["ext", url, title]; }
  var U = {
    cs336: "https://stanford-cs336.github.io/spring2025/", dlsys: "https://dlsyscourse.org/", mlsys: "https://mlsyscourse.org/",
    efficientml: "https://hanlab.mit.edu/courses/2024-fall-65940", scaling: "https://jax-ml.github.io/scaling-book/",
    playbook: "https://huggingface.co/spaces/nanotron/ultrascale-playbook", mleng: "https://github.com/stas00/ml-engineering",
    mamf: "https://github.com/stas00/ml-engineering/tree/master/compute/accelerator/benchmarks",
    allreduce: "https://github.com/stas00/ml-engineering/tree/master/network/benchmarks",
    gpumode: "https://github.com/gpu-mode/lectures", kernelbot: "https://github.com/gpu-mode/reference-kernels",
    leetcuda: "https://github.com/xlite-dev/LeetCUDA", gpuPuzzles: "https://github.com/srush/GPU-Puzzles",
    tritonPuzzles: "https://github.com/srush/Triton-Puzzles", tensorPuzzles: "https://github.com/srush/Tensor-Puzzles",
    trainPuzzles: "https://github.com/srush/LLM-Training-Puzzles", nanovllm: "https://github.com/GeeeekExplorer/nano-vllm",
    bentoml: "https://bentoml.com/llm/", zomi: "https://github.com/Infrasys-AI/AIInfra", aig: "https://caomaolufei.github.io/AIInfraGuide/interview/",
  };

  // ---------------------------------------------------------------- 目标能力
  var ABILITIES = [
    { c: "c-blue", t: "编码与算法", why: "所有面试的第一关，也是最容易被低估的一关。", pass: [
      "LeetCode 中等题 25 分钟内一次写对，困难题能给出可行思路和复杂度",
      "Hot 100 全部完成 + 约 100 道专项，做错的题二刷",
      "20 个推理系统高频组件能现场手写（注意力、采样、Radix Cache、线程池……）",
      "Python 和 C++ 都能写：推理系统的代码两种语言各占一半"],
      verify: "每周限时模拟：中等题 25 分钟一次通过率 ≥ 70%；手撕组件在练习题里判题通过，并在限定时间内完成",
      links: [L("serving", "career/coding", "手撕代码题"), ["practice", "", "练习题库"]] },
    { c: "c-indigo", t: "C++ 与系统编程", why: "开源推理基础库（通信、算子、存储）大量是 C++，读不懂就没法讨论细节。", pass: [
      "现代 C++ 写得地道：RAII、移动语义、智能指针、模板与 constexpr",
      "并发：线程、atomic、内存序、无锁队列、线程池",
      "能读懂并修改 DeepEP、FlashInfer、Mooncake 这一级别的 C++ / CUDA 工程代码",
      "会用 pybind11 / PyTorch C++ 扩展把实现暴露给 Python，会用 sanitizer 和 perf 定位问题"],
      verify: "C++ 练习题判题通过，且 ASan / TSan / UBSan 无报错；在一个开源 C++ 项目里定位并修掉一个小问题",
      links: [L("cpp", "basics/value-raii", "值语义与 RAII"), L("cpp", "concurrency/atomics", "内存序"), L("cpp", "engineering/reading-code", "读懂推理基础库")] },
    { c: "c-orange", t: "GPU 与 CUDA", why: "推理优化最终落在 kernel 和带宽上，面试会追问到硬件数字。", pass: [
      "讲清 SM、warp、内存层次、Tensor Core，记住 H100 / H800 的关键数字",
      "手写归约、转置、分块 GEMM、online softmax、FlashAttention 前向",
      "用 Nsight Compute 找到瓶颈并用数字说明离屋顶线还差多少",
      "Triton 能写融合算子；理解 Hopper 的 TMA、WGMMA、FP8 在做什么"],
      verify: "练习题的 GPU 模拟器检查访存与竞争；真卡性能门槛：归约 ≥ 实测带宽 80%，SGEMM ≥ cuBLAS 70%，Tensor Core HGEMM ≥ cuBLAS 60%，Triton FlashAttention 前向 ≥ FA2 60%",
      links: [L("cuda", "kernels/gemm", "GEMM 优化之路"), L("cuda", "advanced/attention", "FlashAttention"), L("cuda", "tools/profiling", "Nsight")] },
    { c: "c-purple", t: "大模型原理与数值", why: "推理系统的每一处优化都要回到模型结构和数值精度上找依据。", pass: [
      "手推注意力、FFN、RoPE、RMSNorm 的前向与反向",
      "MLA 的低秩压缩与矩阵吸收、MoE 路由与负载均衡、MTP 的原理",
      "FP8 / INT4 量化的误差来源与缩放粒度",
      "对任意模型估算参数量、FLOPs、KV Cache 大小和 decode 的带宽上限"],
      verify: "自测题 ≥ 85%；估算题与实际建模或实测对比误差 ≤ 10%；手推题限时写出",
      links: [L("llm", "transformer/attention-variants", "MQA / GQA / MLA"), L("llm", "transformer/moe", "MoE"), L("llm", "inference/estimation", "估算"), ["practice", "?q=估算", "估算题库"]] },
    { c: "c-green", t: "推理引擎", why: "岗位的主战场：要能从请求到 token 讲清每一步、每一处取舍。", pass: [
      "画出 SGLang / vLLM 从请求到返回 token 的全流程，解释每处设计取舍",
      "手写分页 KV、连续批处理、前缀缓存、分块 prefill、重叠调度、CUDA Graph",
      "自己写的引擎在 GPU 上跑通，并和 SGLang 做性能对比与消融",
      "至少给一个主流推理框架提交过被合入的 PR"],
      verify: "自己的实现贪心输出与 Hugging Face 逐 token 一致；同卡同负载吞吐 ≥ SGLang 的 60%；有消融报告；PR 被合入",
      links: [L("serving", "engine/overview", "从零写推理引擎"), L("minisgl", "overview/architecture", "手写 mini-sglang"), L("serving", "source/sglang", "SGLang 源码")] },
    { c: "c-teal", t: "分布式推理与大规模部署", why: "大模型推理是多机多卡的大系统，系统设计题几乎都落在这里；训练侧的并行也常被追问。", pass: [
      "TP / EP / PP / CP 各自的通信模式与通信量",
      "DeepEP 的高吞吐与低延迟两种模式；RDMA、NVLink 与 NVSHMEM 的角色",
      "PD 分离与 KV 传输、以 KV Cache 为中心的多级缓存架构",
      "训练侧：DP / ZeRO / FSDP、Megatron TP + SP、PP 调度，能算清显存账本和通信量",
      "设计一个数百 B 参数 MoE 模型的在线服务，给出机器数、吞吐和延迟估算"],
      verify: "多进程（CPU 上用 gloo 即可）的 TP / EP / PP / DDP 与单进程数值对齐；实测 all-reduce 总线带宽并解释与理论值的差距；显存账本与实测误差 ≤ 15%",
      links: [L("serving", "distributed/expert-parallel", "专家并行"), L("serving", "distributed/pd-disagg", "PD 分离"), L("train", "data/zero-fsdp", "ZeRO 与 FSDP"), L("train", "practice/strategy", "并行的组合与选择"), L("serving", "comm/nvshmem-deepep", "NVSHMEM 与 DeepEP"), L("serving", "comm/kv-storage", "KV 传输与存储")] },
  ];

  // ---------------------------------------------------------------- 三类岗位
  var DIRS = [
    ["日常工作",
      "调度、KV 管理、并行策略；新模型适配与特性开发",
      "注意力、GEMM、MoE、量化 kernel 与通信算子；Profiling 与端到端调优",
      "大规模部署、PD 分离、KV 缓存池、路由与弹性伸缩；稳定性与成本"],
    ["考察重点",
      "引擎全流程与每处设计取舍；源码细节；手写调度器与缓存",
      "CUDA / Triton 现场手写；硬件关键数字；屋顶线分析与数值精度",
      "系统设计与容量估算；通信与存储；故障处理与扩缩容"],
    ["必读代码",
      "SGLang、vLLM、mini-sglang、FlashInfer 的调用侧",
      "FlashAttention、FlashMLA、DeepGEMM、CUTLASS / CuTe、Triton 教程",
      "Mooncake、NVIDIA Dynamo、LMCache、llm-d、SGLang Model Gateway"],
    ["计划里对应", "第 5～8 周 + 作品 A", "第 2～3、10、13 周 + 作品 C", "第 9、11～12、14 周 + 作品 B"],
  ];

  // ---------------------------------------------------------------- 学习目标分级与验证
  var LEVELS = [
    { c: "c-blue", k: "L1", t: "讲清", d: "用一句话加一个关键数字讲清是什么、为什么，并接住一次追问。",
      how: ["章首自测、自测题库正确率 ≥ 85%", "对着空白页讲 3 分钟，录音回放找漏洞", "整理成面试题卡"] },
    { c: "c-green", k: "L2", t: "写对", d: "不看资料写出能通过测试的实现，边界情况正确。",
      how: ["练习题判题：浏览器、本地、GPU", "GPU 模拟器：越界、竞争、合并访存、bank conflict", "与参考实现逐 token / 逐元素对齐"] },
    { c: "c-orange", k: "L3", t: "做快", d: "限时写出来；在真卡上达到性能门槛；估算与实测误差在范围内。",
      how: ["计时手写：20～45 分钟", "真卡性能门槛：相对 cuBLAS、FA2、SGLang 的比例", "估算题：与实际建模或实测对比，误差 ≤ 10%"] },
    { c: "c-purple", k: "L4", t: "交付", d: "做成别人能复现、能评价的东西，并经得起追问。",
      how: ["作品：基线对比、消融、10 分钟可复现", "PR 被合入、博客、排行榜名次", "模拟面试评分表"] },
  ];
  var TOOLBOX = [
    ["章首自测与自测题库", "概念是否清楚", "各手册章首的自测、大模型手册的自测题库、CUDA 与推理岗面试题库", "每章 / 每周"],
    ["练习题判题", "实现是否正确", "练习题：浏览器里一键判题；本地 judge.py（macOS / WSL2 + GPU）", "每周"],
    ["GPU 模拟器", "访存模式与并发是否正确", "练习题里的 GPU 模拟器：合并访存、bank conflict、竞争检测、栅栏分歧", "第 2～3 周"],
    ["真卡性能门槛", "性能是否达标", "judge.py bench 实测本机带宽与算力作分母；CUDA C++ 题的铜 / 银 / 金档位；Nsight Compute；GPU MODE 排行榜", "第 2、3、7、10、13 周"],
    ["估算题", "定量推理", "练习题里的估算题库（20 道，搜索“估算”）、Scaling Book 各章习题；估算结果与实测对比", "第 4、9、14 周"],
    ["限时手写", "面试时的速度", "计时器 + 手撕组件清单（大多有对应练习题）", "每周"],
    ["作品验收", "端到端交付", "基线对比、消融实验、复现说明、压测报告", "第 7、12、13 周"],
    ["模拟面试", "表达与追问", "推理系统手册「模拟面试」一章：60 分钟四个环节，正确性、深度、数字、沟通四项评分，复盘模板", "第 9 周起每周"],
    ["外部信号", "是否被认可", "PR 合入、博客的阅读与反馈、排行榜名次", "第 8 周起"],
  ];

  // ---------------------------------------------------------------- 参考的课程与教程
  var REFS = [
    ["Stanford CS336：从零构建语言模型", U.cs336, "第 1、3、9 周",
      "作业 1（分词器、模型、优化器，从零训练小模型）当作可选大作业；作业 2（Profiling、Triton 版 FlashAttention2、DDP 与分片优化器）拆到第 3、9 周", "作业自带测试和排行榜"],
    ["CMU 10-414 Deep Learning Systems", U.dlsys, "第 3 周（可选）", "needle 作业：从零写自动微分和 strided NDArray 的 CPU / GPU 后端，补 PyTorch 内部机制", "自动评测"],
    ["CMU 15-442 Machine Learning Systems", U.mlsys, "第 1 周", "通读课表对照查漏：框架、编译、并行、服务的全景", ""],
    ["MIT 6.5940 EfficientML", U.efficientml, "第 4、10 周", "量化、剪枝与稀疏、蒸馏、LLM 部署的讲座；AWQ 与 2:4 稀疏的 lab", "lab 有精度门槛"],
    ["How to Scale Your Model（JAX Scaling Book）", U.scaling, "第 4、9 周", "屋顶线、Transformer 数学、训练与推理的并行，GPU 一章；每章末尾的习题当估算训练", "带答案的习题"],
    ["Hugging Face Ultra-Scale Playbook", U.playbook, "第 9 周", "分布式训练的主线教材：DP → ZeRO → TP / SP → CP → PP → EP；和本站的分布式训练手册对照读，它的实测数据更多", "显存账本与实测对比"],
    ["ML Engineering（Stas Bekman）", U.mleng, "第 2、9、14 周", "硬件、网络、存储、调试；用 mamf-finder 和 all_reduce_bench 实测自己的机器", "实测数字"],
    ["GPU MODE 讲座 + PMPP 第 4 版", U.gpumode, "第 2～3、6、10 周", "性能清单、归约、Tensor Core、CUTLASS / CuTe、FlashInfer、SGLang 性能优化等讲座，配合 PMPP 教材", ""],
    ["GPU MODE 排行榜（KernelBot）", U.kernelbot, "第 13 周", "PMPP 练习题和 kernel 竞赛题，提交到真卡上评测", "真卡排行榜"],
    ["LeetCUDA", U.leetcuda, "第 3、10、13 周", "200 多个 CUDA / Triton / CuTe kernel，按难度挑 20～30 个刷，重点看 HGEMM 与 FA2-MMA", "与 cuBLAS、FA2 的性能对比"],
    ["Puzzles 系列（Sasha Rush）", U.gpuPuzzles, "第 1～3、9 周", "Tensor、GPU、Triton、LLM Training 四套谜题，作为每个阶段的热身", "自带测试"],
    ["nano-vllm", U.nanovllm, "第 5～7 周", "约 1200 行的 vLLM 复刻，与 mini-sglang 对照阅读", ""],
    ["LLM Inference Handbook（BentoML）", U.bentoml, "第 11、14 周", "推理指标、优化手段、部署与运维的概览", ""],
    ["AIInfra（ZOMI 酱）", U.zomi, "第 9、14 周", "中文课程：AI 集群、通信与存储、容器与云原生、分布式训练与推理，含 MFU 建模代码", ""],
    ["AIInfraGuide 面试宝典", U.aig, "第 14～16 周", "约 200 篇真实面经：按主题归类，组成模拟题", "模拟面试"],
  ];

  // ---------------------------------------------------------------- 差异化
  var EDGE = [
    { c: "c-blue", t: "主线：推理系统基本盘", why: "所有候选人都要过；达不到这一线，放大器无从谈起。", pass: [
      "调度、KV 管理、分布式、性能分析四件事讲得清、写得出",
      "C++ / CUDA 达到能读懂、能修改开源基础库的程度",
      "mini-sglang 全链路复刻 + 性能报告，作为最基础的作品"] },
    { c: "c-orange", t: "放大器一：Rust 与系统工程", why: "推理平台的数据面越来越多用 Rust：SGLang 的 Router / Model Gateway、Hugging Face tokenizers 都是 Rust 实现。", pass: [
      "作品 B：用 Rust 写一个 PD 感知、缓存感知的推理网关",
      "把网关里的经验变成给 SGLang Rust 网关的 PR",
      "用数字说话：尾延迟、吞吐、缓存命中率相对基线的提升"] },
    { c: "c-purple", t: "放大器二：大型系统架构", why: "系统设计面试最能拉开差距：PD 分离、KV 缓存池、多租户、全局调度本质上都是分布式系统问题。", pass: [
      "10 道推理系统设计题，每道都有容量估算、故障域和扩缩容方案",
      "用分布式系统的通用语言讲推理系统：调度、缓存、传输、隔离、可观测性",
      "对比两种大规模推理架构：以 KV Cache 为中心的分离式架构，和大规模专家并行 + PD 分离，作为面试谈资"] },
    { c: "c-teal", t: "放大器三：运行时与工具化", why: "推理引擎本身就是一个运行时：事件循环、任务调度、内存池、异步执行（CUDA Stream / Graph）、零拷贝。", pass: [
      "从运行时的视角讲重叠调度、CUDA Graph、KV 内存管理，讲出自己的理解",
      "作品 D（可选）：推理性能可视化 / 调度回放工具，把 profiler 和引擎日志变成可交互的时间线",
      "面试时现场演示工具定位一个真实的性能问题，辨识度很高"] },
  ];

  // ---------------------------------------------------------------- 阶段与逐周
  var PHASES = [
    { c: "c-blue", name: "阶段一 · 基础夯实", weeks: [1, 5] },
    { c: "c-green", name: "阶段二 · 框架深入", weeks: [6, 9] },
    { c: "c-orange", name: "阶段三 · 前沿专题与作品", weeks: [10, 13] },
    { c: "c-pink", name: "阶段四 · 面试冲刺", weeks: [14, 17] },
  ];

  var WEEKS = [
    { t: "诊断 + 数学与 Transformer 复盘 + C++ 起步", g: "摸清自己的底；把大模型的数学和 Transformer 前向复习到能手写。",
      learn: [L("setup", "", "学习环境：一键准备（Mac 可用）"), L("llm", "synthesis/quiz", "自测题库（先做诊断）"), L("llm", "math/linear-algebra", "线性代数"), L("llm", "math/probability", "概率与采样"),
        L("llm", "math/information-theory", "信息论"), L("llm", "math/calculus", "微积分与反向传播"), L("llm", "math/floating-point", "浮点与数值计算"),
        L("llm", "transformer/attention", "注意力机制"), L("llm", "transformer/position", "RoPE"), L("llm", "transformer/norm-residual", "归一化与残差"),
        L("llm", "transformer/ffn", "SwiGLU"),
        L("cpp", "basics/compile-ub", "C++：编译模型与未定义行为"), L("cpp", "basics/value-raii", "C++：值语义与 RAII"),
        L("cpp", "basics/move", "C++：移动语义"), L("cpp", "basics/ownership", "C++：智能指针与所有权"),
        E(U.tensorPuzzles, "Tensor Puzzles（热身）"), L("llm", "training/assignment", "大作业一：从零训练一个小语言模型"), E(U.cs336, "CS336 作业 1（对照）"), E(U.mlsys, "CMU 15-442 课表（对照查漏）")],
      practice: ["llm-stable-softmax", "llm-cross-entropy", "llm-micrograd", "llm-linear-ce-backward", "llm-bf16", "llm-causal-mha", "llm-rope", "llm-rmsnorm", "llm-swiglu",
        "cpp-raii-fd", "cpp-rule-of-five", "cpp-unique-ptr"],
      algo: "数组、哈希、双指针、滑动窗口：25 题",
      out: ["开发环境：本地 NVIDIA GPU（WSL2）+ 按需租用的 Hopper 云主机账号；Mac 上装好练习题环境（practice/env）",
        "开一个技术笔记仓库（后面整理成博客），第一篇：手推 softmax + 交叉熵的反向传播"],
      check: ["L1 用自测题库做一次诊断，把不会的章节标出来，调整后面几周的顺序", "L3 20 分钟手写带因果掩码的多头注意力（numpy）",
        "L1 推导 softmax + 交叉熵的梯度，解释数值稳定为什么要减最大值", "L1 讲清 fp16、bf16、fp8 的位宽分配和各自的风险", "L2 本周的 Python 练习题全部通过（浏览器判题），3 道 C++ 题在 ASan 下通过（本地判题）"] },
    { t: "GPU 架构与 CUDA 基础 + C++ 内存", g: "建立 GPU 的心智模型：线程层级、内存层次、占用率、warp 级编程。",
      learn: [L("cuda", "basics/gpu-architecture", "GPU 架构"), L("cuda", "basics/first-kernel", "第一个 CUDA 程序"), L("cuda", "basics/memory", "内存层次"),
        L("cuda", "basics/execution", "执行模型"), L("cuda", "basics/sync-warp", "同步与 warp 编程"),
        L("cpp", "basics/templates", "C++：模板与编译期派发"), L("cpp", "memory/layout", "C++：对象布局、对齐与缓存"),
        L("cpp", "memory/allocators", "C++：分配器与内存池"), L("cpp", "basics/stl-perf", "C++：标准库的性能视角"),
        L("cpp", "engineering/build-debug", "C++：CMake、sanitizer 与 perf"),
        E(U.gpuPuzzles, "GPU Puzzles（热身）"), E(U.gpumode, "GPU MODE 讲座 1～4、8"), E(U.mamf, "mamf-finder：实测可达算力")],
      practice: ["cu-thread-index", "cu-vector-add", "cu-stencil-smem", "cu-grid-stride", "cu-occupancy", "cu-warp-reduce", "cu-histogram",
        "cpp-dispatch", "cpp-topk", "cpp-arena", "cpp-block-pool"],
      algo: "链表、栈、队列、二分：25 题",
      out: ["向量加法的 CUDA C++ 版本在自己的 GPU 上通过判题，记录带宽占峰值的比例"],
      check: ["L1 讲清 SM、warp、线程块、共享内存、L2、HBM 的关系，说出 H100 的关键数字", "L1 手算一个 kernel 的占用率并指出瓶颈资源",
        "L2 白板写出 warp shuffle 归约和共享内存私有化的直方图", "L2 解释合并访存和 bank conflict，并用练习题里模拟器的统计验证",
        "L3 用 python practice/judge.py bench 实测显存带宽和可达算力，记下来作为后面所有性能门槛的分母"] },
    { t: "经典算子与 Triton + C++ 并发", g: "把优化 kernel 的套路练熟，并学会用 profiler 说话。",
      learn: [L("cuda", "kernels/reduction", "归约"), L("cuda", "kernels/transpose", "转置"), L("cuda", "kernels/gemm", "GEMM 优化之路"),
        L("cuda", "kernels/softmax-norm", "Softmax 与归一化"), L("cuda", "kernels/scan", "前缀和"), L("cuda", "tools/triton", "Triton"),
        L("cuda", "tools/profiling", "Nsight"),
        L("cpp", "concurrency/threads", "C++：线程、锁与条件变量"), L("cpp", "concurrency/atomics", "C++：atomic 与内存序"),
        L("cpp", "concurrency/lockfree-pool", "C++：无锁队列与线程池"),
        L("cuda", "framework/tensor", "PyTorch：张量的内存模型"), L("cuda", "framework/autograd", "PyTorch：autograd 的实现"),
        L("cuda", "framework/dispatcher", "PyTorch：dispatcher 与自定义算子"),
        E(U.tritonPuzzles, "Triton Puzzles"), E(U.leetcuda, "LeetCUDA：归约、SGEMM、softmax"), E(U.dlsys, "CMU DLSys needle 作业（可选）")],
      practice: ["cu-reduction", "cu-transpose-smem", "cu-gemm-tiled", "cu-online-softmax", "cu-block-scan", "cu-triton-softmax", "cu-triton-matmul",
        "cu-est-wave-quant", "cu-est-gemm-traffic", "cpp-bounded-queue", "cpp-spsc-ring", "cpp-thread-pool", "cpp-shared-ptr"],
      algo: "二叉树、DFS、BFS：25 题",
      out: ["四个算子在真卡上的性能报告（归约、转置、GEMM、softmax 的 CUDA C++ 版本），附 Nsight Compute 分析"],
      check: ["L3 45 分钟写出共享内存分块 GEMM 和 online softmax（CUDA C++）", "L1 用 ncu 读懂 memory / compute throughput，说出离屋顶线差在哪",
        "L2 用 Triton 写出融合 softmax 和分块 matmul，说出和 CUDA 写法的分工差异", "L2 C++ 的阻塞队列、SPSC 无锁队列、线程池、shared_ptr 四道题在 TSan 下通过",
        "L3 真卡性能门槛：归约、SGEMM 的 CUDA C++ 版本都达到练习题的银档（归约 ≥ 实测带宽 80%，SGEMM ≥ cuBLAS 70%）"] },
    { t: "现代模型结构与推理原理", g: "把 GQA、MLA、MoE、量化和估算方法吃透，为后面的系统设计打数字基础。",
      learn: [L("llm", "transformer/build-llm", "从零组装大模型"), L("llm", "transformer/attention-variants", "MQA / GQA / MLA"), L("llm", "transformer/moe", "MoE"),
        L("llm", "inference/decoding", "解码与采样"), L("llm", "inference/kv-cache", "KV Cache"), L("llm", "inference/estimation", "参数量与显存估算"),
        L("llm", "inference/quantization", "量化原理"), L("llm", "inference/serving", "推理服务概念"), L("llm", "math/performance-math", "性能数学"),
        E(U.scaling, "Scaling Book：屋顶线、Transformer 数学、推理三章的习题"), E(U.efficientml, "MIT 6.5940 量化讲座（可选）")],
      practice: ["llm-mini-qwen", "llm-gqa", "llm-moe-router", "llm-kv-cache-decode", "llm-param-count", "llm-int4-quant", "llm-roofline", "llm-sampling", "llm-beam-search", "llm-serving-metrics",
        "llm-est-kv-bytes", "llm-est-moe-experts", "llm-est-attn-intensity", "llm-est-decode-bound"],
      algo: "堆、贪心、区间：20 题",
      out: ["一页纸估算：一个 600B 级 MLA + MoE 模型（如 DeepSeek-V3）decode 一步的权重读取量、KV 读取量、FLOPs 与带宽下限"],
      check: ["L1 手推 MLA：KV 为什么能压到 512 + 64 维，矩阵吸收合并了哪些矩阵，decode 时省了什么", "L1 解释 MoE 的 top-k 路由、负载均衡损失，以及无辅助损失的均衡方法",
        "L3 对任意 config.json 算出参数量、每 token FLOPs、KV 字节数", "L1 用屋顶线讲清 prefill 与 decode 的瓶颈差异，以及攒批为什么有效",
        "L3 Scaling Book 屋顶线、Transformer 数学、推理三章的习题独立做对 80%"] },
    { t: "推理引擎原理：从零写 nano engine", g: "亲手实现分页 KV、连续批处理、前缀缓存、采样与流式输出。",
      learn: [L("serving", "engine/overview", "一个请求的一生"), L("serving", "engine/paged-kv", "分页 KV Cache"), L("serving", "engine/batch-layout", "变长批处理"),
        L("serving", "engine/scheduler", "调度器"), L("serving", "engine/prefix-cache", "前缀缓存"), L("serving", "engine/sampler-api", "采样与接口"),
        L("serving", "engine/graphs-compile", "CUDA Graphs 与 torch.compile"),
        E(U.nanovllm, "nano-vllm（对照阅读）")],
      practice: ["sv-block-pool-cow", "sv-batch-layout", "sv-scheduler", "sv-prefix-cache-pool", "sv-stop-strings", "sv-graph-buckets"],
      algo: "回溯、动态规划入门：20 题（累计约 115）",
      out: ["跟着手册写完 nano engine，在 GPU 上跑通并测出吞吐 / 延迟曲线"],
      check: ["L1 讲清连续批处理、分块 prefill、抢占（重算 vs 换出）的取舍", "L1 讲清哈希块与基数树两种前缀缓存的差异",
        "L1 解释 CUDA Graph 为什么只用于 decode，以及补齐的代价",
        "L2 nano engine 的贪心输出与 Hugging Face 逐 token 一致", "里程碑 M1 全部达标"] },
    { t: "手写 mini-sglang（上）：算得对、排得好", g: "对照一个真实、完整的代码库，从零实现模型执行与调度器。",
      learn: [L("minisgl", "overview/architecture", "导读"), L("minisgl", "compute/core", "核心数据结构"), L("minisgl", "compute/kvcache", "KV 池与 page table"),
        L("minisgl", "compute/attention", "注意力后端"), L("minisgl", "compute/engine", "Engine 与采样"), L("minisgl", "schedule/scheduler", "调度器"),
        L("minisgl", "schedule/cache-manager", "CacheManager"), L("minisgl", "schedule/radix-cache", "Radix Cache"), L("minisgl", "schedule/chunked-prefill", "分块 prefill"),
        L("minisgl", "schedule/overlap", "重叠调度")],
      practice: ["ms-req-lengths", "ms-base-op", "ms-weight-stream", "ms-paged-alloc", "ms-attn-metadata", "ms-batched-sampler", "ms-prefill-adder", "ms-cache-req", "ms-radix-cache", "ms-chunk-size", "ms-overlap-loop"],
      algo: "动态规划：20 题",
      out: ["自己的 mini-sglang 仓库：前 12 章的代码与测试全部通过（先自己写，写完再对照手册）"],
      check: ["L1 不看资料画出进程结构和一个请求经过的所有消息", "L1 解释准入控制为什么按最坏情况预留、代价是什么",
        "L1 讲清重叠调度的四个问题各自的触发条件和修法", "L3 40 分钟内写出 Radix Cache 的匹配、插入、加锁、淘汰"] },
    { t: "手写 mini-sglang（下）：服务化与更快", g: "把引擎变成服务，接上 GPU 注意力后端、CUDA Graph、张量并行和 MoE，做性能报告。",
      learn: [L("minisgl", "wrap/assignment", "大作业三：推理引擎的 GPU 性能门槛"), L("minisgl", "serve/message", "消息与 ZMQ"), L("minisgl", "serve/tokenizer", "增量反分词"), L("minisgl", "serve/api-server", "API Server"),
        L("minisgl", "perf/tensor-parallel", "张量并行"), L("minisgl", "perf/gpu-attention", "FlashInfer / FlashAttention"), L("minisgl", "perf/cuda-graph", "CUDA Graph"),
        L("minisgl", "perf/kernels", "自定义 kernel"), L("minisgl", "perf/moe", "fused MoE"), L("minisgl", "perf/benchmark", "基准测试"), L("cpp", "engineering/python-binding", "C++：pybind11 与 PyTorch 扩展"),
        L("cuda", "framework/cuda-runtime", "PyTorch 的 CUDA 运行时"), L("cuda", "framework/compile", "torch.compile"), L("cuda", "framework/compilers", "AI 编译器全景"),
        E(U.gpumode, "GPU MODE 讲座 35 SGLang 性能优化、40 FlashInfer")],
      practice: ["ms-message-serde", "ms-incremental-detok", "ms-sse-stream", "ms-shard-tensor", "ms-flashinfer-meta", "ms-graph-replay", "ms-store-kv-kernel", "ms-moe-align"],
      algo: "图、并查集、拓扑排序：15 题",
      out: ["作品 A：mini-sglang 在 GPU 上跑通 Qwen3，性能报告对比 SGLang 的吞吐、TTFT、TPOT，并做消融（重叠调度、CUDA Graph、Radix Cache 各贡献多少）"],
      check: ["L1 说清增量反分词为什么要保留上下文窗口", "L1 说清 FlashInfer 的 plan / run 分离在解决什么问题",
        "L1 说清 CUDA Graph 漏拷一个输入会怎样、怎样在 CPU 上发现", "L3 同一张卡、同一负载下，mini-sglang 的吞吐达到 SGLang 的 60% 以上", "L4 性能报告里的每个数字都能解释来源"] },
    { t: "SGLang / vLLM 源码 + 第一个 PR", g: "从“写过一个”走到“读懂工业级实现”，并开始出现在开源社区里。",
      learn: [L("serving", "source/sglang", "SGLang 源码导读"), L("serving", "source/vllm", "vLLM V1 源码导读"), L("minisgl", "wrap/next-steps", "与 SGLang 的差距"), L("cpp", "engineering/reading-code", "C++：读懂推理基础库的 C++"),
        L("serving", "ops/new-model", "新模型接入与精度对齐（第一个 PR 的常见选题）"), L("serving", "source/rust-frontend", "vLLM 的 Rust 前端（和作品 B 相关）")],
      practice: ["sv-first-divergence", "sv-array-struct"],
      algo: "字符串、前缀树、单调栈：15 题",
      out: ["源码笔记：SGLang 从 HTTP 请求到返回 token 的调用链（附图），标出和 mini-sglang 的差异",
        "第一个 PR：从文档、测试或可复现的小 bug 开始（SGLang / vLLM / Mooncake 任选）"],
      check: ["L3 5 分钟内在 SGLang 源码里找到调度器、KV 分配、CUDA Graph、模型注册的位置", "L1 讲清 vLLM V1 与 SGLang 在调度和前缀缓存上的主要差异", "L4 PR 已提交"] },
    { t: "分布式推理与训练、通信与存储", g: "掌握多卡多机的并行方式、通信原语和 KV 传输；训练侧的并行也要能讲清。",
      learn: [L("serving", "distributed/tensor-parallel", "张量并行"), L("serving", "distributed/expert-parallel", "专家并行与 DP Attention"), L("serving", "distributed/pp-cp", "流水线与上下文并行"),
        L("serving", "distributed/pd-disagg", "PD 分离与 KV 传输"), L("serving", "distributed/kv-offload", "KV 分层缓存"), L("cuda", "tools/multi-gpu", "多 GPU 与 NCCL"),
        L("cuda", "tools/streams", "流与 CUDA Graphs"),
        L("serving", "comm/interconnect", "GPU 互联与网络"), L("serving", "comm/nccl", "NCCL 算法与定制 all-reduce"), L("serving", "comm/rdma", "RDMA 编程模型"),
        L("serving", "comm/nvshmem-deepep", "NVSHMEM 与 DeepEP"), L("serving", "comm/kv-storage", "KV 传输引擎与分布式存储"),
        L("train", "practice/assignment", "大作业二：DDP、ZeRO-1 与重计算"), L("train", "basics/overview", "显存账本与时间模型"), L("train", "basics/collectives", "集合通信原语"), L("train", "data/zero-fsdp", "ZeRO 与 FSDP"),
        L("train", "model/tensor-sequence", "TP + SP"), L("train", "model/pipeline", "流水线并行"), L("train", "model/moe-ep", "MoE 与专家并行"),
        L("train", "practice/strategy", "并行的组合与选择"), L("train", "practice/frameworks-rl", "框架与 RL 训练系统"),
        E(U.playbook, "Ultra-Scale Playbook（对照阅读）"), E(U.trainPuzzles, "LLM Training Puzzles"), E(U.allreduce, "all_reduce_bench：实测通信带宽"), E(U.cs336, "CS336 作业 2 的 DDP 与分片优化器部分")],
      practice: ["sv-tp-mlp", "sv-ep-dispatch", "sv-ring-attention", "sv-kv-transfer-plan", "sv-kv-offload", "cu-ring-allreduce", "cu-stream-schedule", "cu-trace-analysis",
        "sv-est-tp-comm", "sv-est-ep-a2a", "sv-est-pp-bubble", "sv-est-pd-transfer", "llm-est-train-compute", "llm-est-train-memory",
        "tr-ring-allreduce", "tr-ddp-buckets", "tr-zero-partition", "tr-1f1b-schedule", "sv-allreduce-choice"],
      algo: "错题重做 + 每周 2 场限时模拟",
      out: ["估算文档：8 卡节点上 TP=8 与 EP=8 部署同一个 MoE 模型，每步的通信量与耗时对比"],
      check: ["L1 讲清 all-reduce、all-gather、reduce-scatter、all-to-all 的通信量与适用场景", "L1 讲清 DeepEP 高吞吐与低延迟两种模式为什么这样设计",
        "L1 讲清 PD 分离的收益、代价和 KV 传输方案", "L3 算出 70B 模型用 ZeRO-3 与 TP + PP 训练时每卡的显存账本",
        "L2 从零实现 DDP（梯度分桶 + 通信与计算重叠），多进程结果与单进程对齐", "L3 在多卡机器上用 judge.py bench 实测 all-reduce 总线带宽，解释与理论值的差距", "里程碑 M2 全部达标"] },
    { t: "前沿专题一：大规模 MoE 推理", g: "把 MLA、FP8、大规模专家并行和 MTP 这一套开源推理栈读到能讨论细节、能提改进的程度。",
      learn: [L("serving", "moe/mla", "MLA 推理：两条计算路径与 FlashMLA"), L("serving", "moe/fp8-gemm", "FP8 细粒度量化与 DeepGEMM"),
        L("serving", "moe/ep-deploy", "大规模 EP 部署：分层 EPLB 与双 batch 重叠"), L("serving", "moe/mtp-sparse", "MTP 与稀疏注意力"),
        L("serving", "moe/case-study", "复盘：公开的大规模 MoE 推理系统"),
        L("serving", "frontier/new-models", "新一代开源模型：压缩注意力、超连接与新的 MoE"), L("serving", "frontier/spec-next", "投机解码的新做法"),
        L("llm", "transformer/attention-variants", "MLA 回顾"), L("cuda", "advanced/attention", "FlashAttention 与推理算子"), L("cuda", "advanced/async-hopper", "Hopper 异步拷贝与 TMA"),
        L("cuda", "advanced/tensor-core", "Tensor Core 与 mma"), L("cuda", "advanced/quantization", "量化与 GEMV"), L("serving", "topics/speculative", "投机解码进阶"),
        E(U.leetcuda, "LeetCUDA：HGEMM、FA2-MMA"), E(U.gpumode, "GPU MODE 讲座 36 CUTLASS 与 FA3、57 CuTe"), E(U.efficientml, "MIT 6.5940 AWQ lab（可选）")],
      practice: ["sv-est-mla-paths", "sv-eplb-packing", "cu-flash-attn", "cu-paged-decode", "cu-mma-layout", "cu-async-pipeline", "cu-gemv-int4", "sv-spec-verify", "sv-tree-verify", "sv-est-spec-speedup",
        "sv-est-v4-kv", "sv-adaptive-verify"],
      algo: "每周 2 场限时模拟",
      out: ["《大规模 MoE 推理系统复盘》：以公开的 DeepSeek-V3 推理系统为例，PD 分离、EP 规模、双 micro-batch 重叠、负载均衡，每个设计都配估算数字",
        "租一台 Hopper 机器跑通 FlashMLA、DeepGEMM 的 benchmark，读懂它们的主循环"],
      check: ["L1 讲清 FlashMLA 解决什么瓶颈、和普通分页 decode 的区别", "L1 讲清 DeepGEMM 的细粒度 FP8 缩放与 JIT 的动机",
        "L1 讲清 MTP 如何用于投机解码、DSA 的索引器在选什么", "L1 回答：把这套推理系统搬到另一种硬件上，哪些设计要改",
        "L3 在 Hopper 上跑 FlashMLA、DeepGEMM 的官方 benchmark，复现公开数字的 80% 以上"] },
    { t: "前沿专题二：分离式架构、长上下文与 RL 推理", g: "吃透以 KV Cache 为中心的分离式架构，以及长上下文与 RL 场景的推理问题。",
      learn: [L("serving", "frontier/disagg-sched", "分离式架构的全局调度"), L("serving", "frontier/linear-attn", "线性注意力与混合架构"),
        L("serving", "frontier/low-bit", "低比特推理与 QAT"), L("serving", "frontier/rl-async", "异步 RL 与权重同步"), L("serving", "comm/kv-storage", "KV 传输引擎与分布式存储"),
        L("serving", "distributed/pd-disagg", "PD 分离回顾"), L("serving", "distributed/kv-offload", "KV 分层缓存"), L("serving", "topics/long-context", "长上下文与 KV 淘汰"),
        L("serving", "topics/rl-rollout", "RL 训练中的推理"), L("serving", "topics/deterministic", "确定性推理：与 batch 无关"), L("train", "practice/frameworks-rl", "框架与 RL 训练系统"), L("serving", "perf/benchmark", "压测与 SLO"),
        L("minisgl", "wrap/assignment-hybrid", "大作业四（可选）：给 mini-sglang 接入 Qwen3.5 的文本部分"),
        E(U.bentoml, "LLM Inference Handbook")],
      practice: ["sv-ttft-router", "sv-est-lowbit-deploy", "sv-cache-aware-router", "sv-kv-block-keys", "sv-kv-eviction", "sv-rollout-sharing", "tr-grpo-advantage", "tr-qkv-reshard", "sv-memory-plan", "sv-capacity-plan", "sv-step-breakdown", "sv-json-fsm"],
      algo: "每周 2 场限时模拟",
      out: ["《分离式推理架构分析》：调度器、KV 池、传输引擎，对比 Mooncake、NVIDIA Dynamo、LMCache 三种方案",
        "在 SGLang 或 vLLM 里用 Mooncake 做一次 PD 分离实验（单机多卡即可），记录 TTFT / TPOT 的变化"],
      check: ["L1 讲清以 KV Cache 为中心的调度在优化什么目标、有哪些约束", "L1 讲清稀疏注意力（NSA、MoBA）与线性注意力（Gated DeltaNet 一类）分别怎样降低长上下文的代价",
        "L1 讲清 RL rollout 和在线服务的差异，以及权重更新要解决什么",
        "L4 PD 分离实验报告：TTFT、TPOT 相对不分离的变化，并能解释原因"] },
    { t: "作品冲刺一：Rust 推理网关", g: "做出最能体现系统工程能力的作品，并把经验反馈到开源项目。",
      learn: [L("serving", "career/portfolio-guide", "作品指南：设计文档与里程碑"), L("serving", "engine/prefix-cache", "缓存感知的调度与路由"), L("serving", "distributed/pd-disagg", "PD 分离"), L("serving", "career/projects", "作品集建议")],
      practice: ["sv-cache-aware-router", "sv-capacity-plan"],
      algo: "每天 2 题保持手感",
      out: ["作品 B：OpenAI 兼容与流式、缓存感知路由、PD 配对、指标与压测报告", "第 2、3 个 PR（优先 SGLang 的 Rust 网关或 KV 传输相关项目）"],
      check: ["L4 压测报告有基线对比（轮询、最少连接）", "L4 README 能让陌生人 10 分钟跑起来", "L1 能讲清每个设计取舍和一个失败的尝试"] },
    { t: "作品冲刺二：GPU 算子 + 技术博客", g: "证明能下到 GPU 底层，并把前 12 周的积累写成公开文章。",
      learn: [L("cuda", "advanced/attention", "推理算子"), L("cuda", "career/projects", "CUDA 作品集"), L("cuda", "tools/profiling", "Nsight"),
        E(U.kernelbot, "GPU MODE 排行榜（KernelBot）")],
      practice: [],
      algo: "每天 2 题",
      out: ["作品 C：MLA decode 算子（Triton 或 CUDA）或分块缩放的 FP8 GEMM，含对拍测试与 benchmark",
        "发布 3 篇技术博客：mini-sglang 性能报告、大规模 MoE 推理复盘、作品 B 或 C", "（可选）作品 D：推理性能可视化工具"],
      check: ["L3 作品 C 的性能占峰值比例有数字，并用 ncu 解释剩余差距",
        "L3（可选）在 GPU MODE 排行榜提交一道题，记录名次", "里程碑 M3 全部达标"] },
    { t: "系统设计 + 简历 + 练手面试", g: "把知识组织成面试能用的形状。",
      learn: [L("serving", "career/system-design", "系统设计题"), L("serving", "career/design-answers-1", "系统设计参考答案（一）"), L("serving", "career/design-answers-2", "系统设计参考答案（二）"), L("serving", "career/mock-exams", "模拟面试套卷"),
        L("serving", "ops/deploy", "生产部署与运维"), L("serving", "ops/frameworks", "推理框架选型"), L("serving", "career/interview", "推理岗面试题库"), L("serving", "career/projects", "作品集与简历"), L("serving", "career/mock-interview", "模拟面试：评分表与复盘"),
        E(U.zomi, "ZOMI AIInfra：容器与云原生"), E(U.bentoml, "LLM Inference Handbook：部署与运维")],
      practice: ["sv-est-cluster-size", "sv-capacity-plan", "sv-memory-plan"],
      algo: "每周 3 场限时模拟",
      out: ["10 道系统设计题的答案（架构图 + 估算）", "简历定稿（一页），每个项目三段式：问题 → 方案 → 数字", "投递 2～3 家同类岗位练手"],
      check: ["L3 每道系统设计题 45 分钟内讲完且有容量估算", "L4 请人做 2 次模拟面试并复盘"] },
    { t: "基础追问冲刺 + 第一批正式面试", g: "把知识点磨成“一句话答案 + 能接住追问”。",
      learn: [L("serving", "career/interview", "推理岗面试题库"), L("llm", "synthesis/quiz", "大模型自测题库"), L("cuda", "career/interview", "CUDA 面试题库"), L("cpp", "engineering/interview", "C++ 面试高频题"),
        L("serving", "career/hardware", "硬件与生态速查"), L("serving", "career/mock-interview", "模拟面试评分表"),
        E(U.aig, "AIInfraGuide 面试宝典（按主题做模拟题）")],
      practice: [],
      algo: "Hot 100 二刷中做错的题",
      out: ["面试题卡：每个知识点一句话答案 + 一个追问，约 150 张", "第一批正式投递（优先内推）"],
      check: ["L4 模拟面试 ≥ 2 次，评分表四项都 ≥ 3 分", "L4 每场真实面试后 24 小时内写复盘，补上没答好的点"] },
    { t: "第二批正式面试", g: "最想去的岗位放在状态最好的时候面。",
      learn: [L("serving", "distributed/expert-parallel", "专家并行回顾"), L("llm", "transformer/moe", "MoE 回顾"), L("cuda", "advanced/attention", "推理算子回顾")],
      practice: ["llm-causal-mha", "llm-sampling", "ms-radix-cache", "py-blocking-queue", "cu-gemm-tiled"],
      algo: "每天 2 题 + 手撕组件轮换",
      out: ["第二批投递（优先内推）", "针对岗位描述，把相关论文各准备 10 个可能的追问和答案"],
      check: ["L3 限时手撕一遍：注意力、top-p 采样、Radix Cache、线程池、分块 GEMM", "L1 每个项目准备 3 个难点、3 个数字、1 个失败的尝试"] },
    { t: "缓冲、复盘与决策", g: "应对加面、补面，做出选择。",
      learn: [L("serving", "career/projects", "学习计划与作品集")],
      practice: [],
      algo: "按面试反馈补弱项",
      out: ["加面 / 补面准备", "比较 offer：团队方向（推理系统、训练基础设施、存储与网络）、成长空间"],
      check: ["L4 整理 17 周的笔记与作品，形成可长期维护的个人主页"] },
  ];

  var MILESTONES = [
    { c: "c-blue", when: "第 5 周末", t: "M1 基础合格", items: ["Python、大模型、CUDA 三本的练习题通过率 ≥ 80%", "30 分钟白板写出带 KV Cache 的 GQA 注意力 + RoPE",
      "45 分钟写出 warp 归约与分块 GEMM（CUDA C++）", "算法题累计约 115 道，中等题 25 分钟通过率 ≥ 70%", "能用数字讲清 prefill 与 decode 的瓶颈", "真卡：归约 ≥ 实测带宽 80%，SGEMM ≥ cuBLAS 70%；估算题误差 ≤ 10%"] },
    { c: "c-green", when: "第 9 周末", t: "M2 引擎合格", items: ["自己的 mini-sglang 在 GPU 上跑通，性能报告完成", "推理系统与 mini-sglang 的练习题通过率 ≥ 80%",
      "画出 SGLang 全流程并逐一解释设计取舍", "第 1 个 PR 已提交",
      "mini-sglang 同卡同负载吞吐 ≥ SGLang 60%；从零实现的 DDP 与单进程对齐"] },
    { c: "c-orange", when: "第 13 周末", t: "M3 作品合格", items: ["作品 B、C 完成，3 篇技术博客发布", "PR ≥ 3，至少 1 个被合入",
      "两份前沿专题复盘能脱稿各讲 15 分钟", "达到这里就可以开始投递，不必等到第 15 周"] },
    { c: "c-pink", when: "第 16 周", t: "M4 面试就绪", items: ["算法题约 200 道，Hot 100 二刷完成", "10 道系统设计题、模拟面试 ≥ 6 次",
      "题卡约 150 张、精读清单全部读完", "每个项目能经受 30 分钟的连续追问", "最近 3 次模拟面试评分四项都 ≥ 3 分"] },
  ];

  var PROJECTS = [
    { c: "c-green", t: "作品 A · mini-sglang 全链路复刻", why: "必做（第 6～7 周）。证明理解推理引擎的每一个环节。", pass: [
      "按手册从零实现（先自己写，写完再对照），GPU 上跑通 Qwen3，输出与 Hugging Face 逐 token 一致",
      "与 SGLang 对比吞吐、TTFT、TPOT；消融：重叠调度、CUDA Graph、Radix Cache、分块 prefill 各贡献多少",
      "交付：代码仓库 + 性能报告 + 一篇博客"], links: [L("minisgl", "overview/architecture", "手写 mini-sglang"), L("minisgl", "perf/benchmark", "基准测试与消融")] },
    { c: "c-orange", t: "作品 B · PD 感知的 Rust 推理网关", why: "差异化（第 12 周）。体现系统工程与 Rust 能力，直接对接真实推理框架。", pass: [
      "OpenAI 兼容接口与 SSE 流式；缓存感知路由（近似前缀树）+ 负载均衡",
      "prefill / decode 实例配对与 KV 传输协调（对接 SGLang 的 PD 分离）；健康检查、熔断、重试；Prometheus 指标",
      "压测：对比轮询与最少连接的 TTFT、吞吐、缓存命中率；故障注入测试",
      "加分：思路或代码贡献到 SGLang 的 Rust 网关"], links: [L("serving", "career/portfolio-guide", "作品指南"), L("serving", "engine/prefix-cache", "缓存感知路由"), L("serving", "distributed/pd-disagg", "PD 分离"), ["practice", "sv-cache-aware-router", "练习：缓存感知路由"]] },
    { c: "c-purple", t: "作品 C · GPU 算子", why: "深度（第 13 周）。证明能下到 GPU 底层，而不只会调用库。", pass: [
      "二选一：MLA decode 算子（参考 FlashMLA 的思路，先 Triton 后 CUDA），或分块缩放的 FP8 GEMM（参考 DeepGEMM）",
      "与参考实现对拍；在 Hopper 上给出带宽或 TFLOPS 占峰值的比例",
      "用 Nsight Compute 解释剩余差距和下一步优化方向"], links: [L("serving", "career/portfolio-guide", "作品指南"), L("cuda", "advanced/attention", "推理算子"), L("cuda", "advanced/async-hopper", "Hopper 异步拷贝"), L("cuda", "career/projects", "CUDA 作品集")] },
    { c: "c-teal", t: "作品 D · 推理性能可视化工具（可选）", why: "加分项。把工程工具化能力变成面试时可以现场演示的东西。", pass: [
      "把 torch profiler trace 与引擎日志变成可交互时间线：每步 batch 组成、KV 占用、CPU / GPU 空闲、请求 TTFT 分解",
      "直接加载 SGLang / vLLM 的日志与 trace，给出自动诊断（例如 CPU 开销占比过高、CUDA Graph 未命中）",
      "交付：在线 demo + 用它定位一个真实性能问题的案例文章"], links: [L("serving", "career/portfolio-guide", "作品指南"), L("serving", "perf/profiling", "Profiling 推理引擎"), ["practice", "cu-trace-analysis", "练习：时间线分析"]] },
    { c: "c-pink", t: "开源贡献（贯穿第 8～16 周）", why: "面试官能直接读到你的代码，比任何描述都有说服力。", pass: [
      "目标 3～5 个 PR，至少 1～2 个非文档的实质修改",
      "路径：文档与测试 → 复现并修 bug → 小功能；复现步骤、测试和基准数据写进 PR 描述",
      "关注 SGLang（含 Rust 网关）、vLLM、FlashInfer、Mooncake 等项目的 issue"], links: [L("serving", "source/sglang", "SGLang 源码导读"), L("serving", "source/vllm", "vLLM 源码导读")] },
  ];

  var ALGO = ["第 1 周：数组、哈希、双指针、滑动窗口（25）", "第 2 周：链表、栈、队列、二分（25）", "第 3 周：二叉树、DFS / BFS（25）",
    "第 4 周：堆、贪心、区间（20）", "第 5 周：回溯、动态规划入门（20）", "第 6 周：动态规划（20）", "第 7 周：图、并查集、拓扑排序（15）",
    "第 8 周：字符串、前缀树、单调栈（15）", "第 9～13 周：每周 2 场限时模拟 + 错题重做（约 35）", "第 14～16 周：Hot 100 二刷错题，面试前每天 2 题保持手感"];
  var HANDWRITE = [
    ["数值稳定的 softmax / logsumexp", "llm-stable-softmax"], ["带因果掩码的多头 / GQA 注意力 + KV Cache", "llm-kv-cache-decode"], ["RoPE", "llm-rope"],
    ["RMSNorm / LayerNorm", "llm-rmsnorm"], ["temperature / top-k / top-p 采样", "llm-sampling"], ["束搜索", "llm-beam-search"], ["BPE 训练与编码", "llm-bpe"],
    ["LRU 缓存", "py-lru-cache"], ["Radix Cache", "ms-radix-cache"], ["分页 KV 块分配器（引用计数、写时复制）", "sv-block-pool-cow"],
    ["连续批处理调度器", "sv-scheduler"], ["MoE 路由与分发", "llm-moe-router"], ["投机解码验证", "sv-spec-verify"], ["阻塞队列 / 线程池", "py-blocking-queue"],
    ["无锁单生产者单消费者队列（C++）", "cpp-spsc-ring"], ["线程池（C++，future 与异常传递）", "cpp-thread-pool"], ["CUDA：归约、转置、分块 GEMM", "cu-gemm-tiled"], ["online softmax（CUDA / Triton）", "cu-online-softmax"],
    ["FlashAttention 前向（分块）", "cu-flash-attn"], ["ring all-reduce", "cu-ring-allreduce"], ["动态批处理器（asyncio）", "py-dynamic-batcher"]];
  var DESIGN = ["600B 级 MoE 模型的在线推理服务：PD 分离 + 大规模 EP，给出机器数、吞吐、延迟",
    "以 KV Cache 为中心的多级缓存池：GPU / CPU / SSD 分层、跨机传输、淘汰与一致性",
    "全局调度与缓存感知的推理网关：路由策略、负载均衡、故障转移、灰度发布",
    "多租户 LoRA 服务：适配器加载与换出、批处理、隔离与计费",
    "RL rollout 系统：训练与推理共用集群、权重同步、长尾请求、弹性",
    "百万 token 长上下文服务：上下文并行、稀疏注意力、KV 卸载、首 token 延迟",
    "投机解码服务化：草稿模型部署、接受率监控、与批处理的相互影响",
    "结构化输出与工具调用服务：约束解码的开销、流式解析、超时与重试",
    "推理可观测性与自动扩缩容：指标体系、SLO、容量预测、冷启动",
    "跨地域多集群推理平台：流量调度、模型分发、容灾与成本优化"];
  var PAPERS = [
    "★ Orca：迭代级调度（OSDI'22）", "★ vLLM：PagedAttention（SOSP'23）", "★ SGLang：RadixAttention（NeurIPS'24）",
    "★ Sarathi-Serve：分块 prefill（OSDI'24）", "★ DistServe / Splitwise：PD 分离（OSDI'24 / ISCA'24）", "★ FlashAttention 1 / 2 / 3",
    "★ DeepSeek-V2 / V3 技术报告（MLA、MoE、MTP、FP8）", "★ Mooncake：以 KV Cache 为中心的分离式架构（FAST'25）", "★ Megatron-LM 与 ZeRO：训练侧的并行与显存",
    "FlashInfer（MLSys'25）", "DeepSeek 开源推理系统概览与 FlashMLA、DeepEP、DeepGEMM", "Insights into DeepSeek-V3（ISCA'25，硬件与模型协同）",
    "NVIDIA Dynamo、LMCache、llm-d 的设计文档", "稀疏与线性注意力：NSA、MoBA、Gated DeltaNet", "Medusa 与 EAGLE 1 / 2 / 3：投机解码",
    "SmoothQuant、AWQ、GPTQ：量化", "GShard / Switch Transformer：MoE 与专家并行", "DeepSeek-R1 与 GRPO：推理模型与 RL",
    "HybridFlow（verl）：RL 训练框架中的推理"];
  var TIMELINE = ["第 8 周起：在开源社区和博客里留下可检索的痕迹；整理内推渠道（同事、社区、技术群）",
    "第 13～14 周：投 2～3 家同类岗位练手，熟悉面试节奏", "第 15 周：第一批正式投递（优先内推），用结果调整最后两周的重点",
    "第 16 周：第二批正式投递，最想去的岗位放在状态最好的时候", "每场面试后 24 小时内复盘：问了什么、答得如何、要补什么",
    "招聘窗口不确定时，以“M3 达标即可投递”为准"];
  var RESUME = ["一页；第一屏放目标方向（推理系统 / AI Infra）、作品和开源贡献，再放过往经历",
    "每个项目三段式：问题（为什么难）→ 方案（关键设计）→ 数字（吞吐、延迟、成本、规模）",
    "过往经历用推理系统的语言重述：调度、内存与缓存、异步执行、网络传输、可观测性、稳定性",
    "准备 3 个故事：一次性能优化、一次复杂系统设计、一次线上问题排查，每个都有数字",
    "GitHub、博客、作品 demo、PR 链接直接写进简历"];
  var RHYTHM = [["c-blue", "7 h", "算法题：工作日每天 1 小时（约 2 题）"], ["c-green", "14 h", "主线学习：章节 + 练习题 + 验收清单"],
    ["c-orange", "6 h", "作品 / 开源：周末集中推进"], ["c-purple", "3 h", "输出与复盘：周笔记、博客、题卡；周日对照验收清单打勾"]];
  var BUILD = [
    { c: "c-indigo", t: "P0 · C++ 进阶手册（已完成）", why: "15 章 + 11 道本地判题的 C++ 练习（ASan / UBSan / TSan）。对应第 1～3 周。", pass: [
      "现代 C++ 核心：值语义、RAII、移动、智能指针、模板与 constexpr", "内存：对象布局、对齐、分配器与内存池",
      "并发：线程、atomic、内存序、无锁队列、线程池与协程", "工程：CMake、测试、sanitizer、perf；pybind11 与 PyTorch C++ 扩展；阅读开源基础库的方法"] },
    { c: "c-orange", t: "P0 · 结果验证工具（已完成）", why: "对应全程。把验收从“自己觉得会了”变成可判定的数字。", pass: [
      "✓ 估算题库（20 道，已上线）：训练算力与 MFU、训练显存、KV 账本、MoE 读专家量、注意力访存比、decode / prefill 下限、GEMM 波次与访存、TP / EP 通信、PD 传输、流水线气泡、投机解码、部署规模",
      "✓ 真卡性能档位（已上线）：CUDA C++ 题在 GPU 上按本机实测带宽或同形状 cuBLAS 定铜、银、金三档",
      "✓ 本机基准脚本（已上线）：judge.py bench 测显存带宽、可达算力、多卡 all-reduce 总线带宽",
      "✓ 模拟面试评分表与复盘模板（已上线）：推理系统手册的「模拟面试」一章"] },
    { c: "c-green", t: "P0 · 分布式训练手册（已完成）", why: "11 章。每种并行都从零实现，多进程在 CPU 上与单进程逐项对齐（前向、损失、梯度）。对应第 9 周，也支撑 RL 推理。", pass: [
      "总论与显存账本：参数、梯度、优化器状态、激活", "集合通信原语与 NCCL；DP / DDP；ZeRO 1 / 2 / 3 与 FSDP",
      "Megatron TP + SP、PP 调度（1F1B、交错、零气泡）、CP 与长序列训练、MoE 与 EP", "混合精度与 FP8 训练、重计算与卸载；3D 并行策略选择；Megatron-LM、DeepSpeed、torchtitan、verl 实战",
      "验证方式沿用推理系统手册：多进程在 CPU 上与单进程数值对齐，显存账本与实测对比"] },
    { c: "c-teal", t: "P0 · 通信与存储（已完成）", why: "推理系统手册新增“通信与存储”5 章，α-β 模型、路由与缓存的模拟都实跑验证。对应第 9 周。", pass: [
      "RDMA 与 GPUDirect RDMA、NVLink / NVSwitch 与 NCCL 的算法", "NVSHMEM 与 DeepEP 的实现", "KV 传输引擎与 KV 缓存存储（Mooncake Transfer Engine、3FS）"] },
    { c: "c-blue", t: "P1 · 前沿专题：大规模 MoE 推理（已完成）", why: "推理系统手册新增 5 章，MLA 等价性、FP8 误差、EPLB、MTP / DSA 的代价和公开系统的核对都实跑验证。对应第 10 周。", pass: [
      "MLA 与 FlashMLA", "FP8 细粒度量化与 DeepGEMM", "DeepEP 与大规模专家并行、EPLB", "MTP 与稀疏注意力（NSA、DSA）", "开源推理系统复盘与估算"] },
    { c: "c-purple", t: "P1 · 前沿专题：分离式架构、长上下文与 RL 推理（已完成）", why: "推理系统手册新增 4 章，路由、配比、线性注意力、QAT、异步 RL 的模拟都实跑验证。对应第 11 周。", pass: [
      "KV 中心的分离式架构：Mooncake、NVIDIA Dynamo、LMCache 对比", "稀疏与线性注意力的推理实现", "超大 MoE 的低比特推理：INT4 QAT、FP4", "RL rollout、权重同步与训练推理一体化"] },
    { c: "c-orange", t: "P1 · PyTorch 内部机制与 AI 编译器（已完成）", why: "CUDA 手册新增“框架与编译器”6 章。对应第 3、7 周。", pass: [
      "张量、stride 与视图；autograd 引擎；dispatcher 与自定义算子；CUDA 显存分配器", "torch.distributed 与 torchrun",
      "计算图优化与算子融合；torch.compile（Dynamo + Inductor）；TVM / MLIR / XLA 的思路；TileLang 与 CuTe DSL"] },
    { c: "c-teal", t: "P1 · 大作业（最少脚手架，已完成）", why: "仓库的 assignments/ 目录：只给接口、测试和评分脚本，不给骨架；参考实现不公开，测试用参考实现校验过。对应第 1、9 周。", pass: [
      "从零训练一个小模型：BPE、Transformer、AdamW、训练循环，在限定时间内把验证集 loss 降到目标值",
      "训练系统：DDP + ZeRO-1 + 激活重计算，测吞吐与显存并与估算对比",
      "推理引擎：沿用手写 mini-sglang，补上 GPU 上的性能门槛",
      "接入混合架构：给 mini-sglang 接入 Qwen3.5 的文本部分（Gated DeltaNet + 门控注意力、按请求的状态池），与 transformers 逐 token 一致"] },
    { c: "c-red", t: "P1 · 作品指南（已完成）", why: "推理系统手册的“作品指南”一章。对应第 8、12、13 周。", pass: [
      "作品 B、C、D 的设计文档模板、里程碑和验收指标", "开源贡献入门：各项目的代码导览、如何挑 issue、PR 的写法"] },
    { c: "c-pink", t: "P2 · 面试题库扩充（已完成）", why: "对应第 14～16 周。", pass: [
      "✓ 系统设计 10 题的完整参考答案（架构图 + 可运行的估算）：推理系统手册“系统设计参考答案（一）（二）”", "✓ 手撕 21 题全部配有练习题（含 C++ 的无锁队列、线程池）",
      "✓ 模拟面试套卷：三套按真实结构组好的题（编码 + 追问 + 系统设计 + 项目），附要点与章节链接", "✓ 追问清单：推理岗面试题库按主题整理的 60 题；算法题单见本页面试准备里的“算法题：约 200 道，分周推进”"] },
    { c: "c-indigo", t: "P2 · 推理系统手册补充（已完成）", why: "推理系统手册新增“生产与生态”4 章，大模型手册新增“剪枝、2:4 稀疏与蒸馏”。对应第 14 周。", pass: [
      "生产部署与运维：Kubernetes 上的推理服务、模型加载加速、弹性伸缩、灰度与可观测性", "推理框架选型：vLLM、SGLang、TensorRT-LLM、LMDeploy 的取舍",
      "多 LoRA 服务", "端侧推理：llama.cpp 与 GGUF、MLX、ExecuTorch", "剪枝、2:4 稀疏与蒸馏（大模型手册量化一章的扩展）"] },
  ];

  return {
    BOOK: BOOK, U: U, ABILITIES: ABILITIES, DIRS: DIRS, LEVELS: LEVELS, TOOLBOX: TOOLBOX,
    REFS: REFS, EDGE: EDGE, PHASES: PHASES, WEEKS: WEEKS, MILESTONES: MILESTONES, PROJECTS: PROJECTS,
    ALGO: ALGO, HANDWRITE: HANDWRITE, DESIGN: DESIGN, PAPERS: PAPERS, TIMELINE: TIMELINE, RESUME: RESUME,
    RHYTHM: RHYTHM, BUILD: BUILD
  };
})();
